### ISSUE TITLE
what are all need to be done to get query-server deployable

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/query-server#10]
@enigmaeth @mariobehling 
this is in regards to issue https://github.com/fossasia/open-event-orga-server/issues/2675
so what all are left to get the query server hosted?
If it is deployable. can I work on deploying the query-server

**Comment by abhishek1995s** [comment]
It can be deployed even in this form . But it is better to wait till we complete rest. In the case of using a a front end a web interface might be needed. So django or flask framework will be suitable for that.

**Comment by niranjan94** [comment]
I'll leave getting the `query-server` to a deploy-able state to you guys :) 

But make sure it is, **_at minimum_** deploy-able to a docker infrastructure.

**Comment by enigmaeth** [comment]
@mariobehling The server has been deployed here : https://query-server.herokuapp.com/
