### ISSUE TITLE
app not executing on Python 3.x

### ISSUE THREAD

**Issue by pratik0509** [fossasia/query-server#123]
README.md shows that :

> Dependencies
>-----------------------
>- Python 2.x or Python 3.x
>- Node.js
>- Pip
>- Flask
>- BeautifulSoup4

 But dependencies using pip could not be installed for python3.x .

Quoting the error message :

>File "/tmp/pip-build-s4ac1_v3/librabbitmq/setup.py", line 191
>        except Exception, exc:

This is because librabbitmq is not supported in Python3.x version.
Please change the README.md .

**Comment by cclauss** [comment]
The librabbitmq code on GitHub has this problem fixed but that fix is not in the current librabbitmq release.

**Comment by pratik0509** [comment]
@cclauss Although it has been fixed but it is still not in the release, so the current version README.md should conform to latest release version of librabbitmq . Please correct me if I am mistaken.

**Comment by cclauss** [comment]
Hi @pratik0509 You are correct...  I was writing too fast and did not express myself clearly.  As you can see above, I have commented on an issue in upstream.  However, that issue has been for a year and a half...

**Comment by cclauss** [comment]
The dependency `mechanize` is also not Python 3 compatible...

https://github.com/fossasia/query-server/blob/master/requirements.txt#L12

**Comment by Pk13055** [comment]
@pratik0509 Can you close this issue, given the latest Python3 port PR (#152).

**Comment by cclauss** [comment]
Our Travis tests fail on Python 3:

https://github.com/fossasia/query-server/pull/168/files
https://travis-ci.org/fossasia/query-server/builds/278811497
This issue should be reopend and should remain open until our Travis tests pass on Python 3.

**Comment by pratik0509** [comment]
Sorry. Failed to notice that.

**Comment by cclauss** [comment]
Did #177 close this issue or is there another problem?

**Comment by pratik0509** [comment]
Hi @cclauss can you please elaborate on the point? I am unable to comprehend your statement.

**Comment by cclauss** [comment]
I think we can close this issue.
