### ISSUE TITLE
app/scraper.py is not Python 3 compatible

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#125]
This script raises a NameError when run in Python 3.

**Comment by Pk13055** [comment]
Can I pick this up? Make it cross compatible across Python2/3.x
? @niranjan94

**Comment by AnshulMalik** [comment]
Yes @Pk13055 feel free

**Comment by Pk13055** [comment]
@cclauss This issue is outdated given the modular nature of the scrapers now. Please close this issue.

**Comment by cclauss** [comment]
Closed with #197
