### ISSUE TITLE
Are there unused dependancies in requirements.txt?

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#126]
[README.md](..#dependencies) currently lists the project dependencies as:
Dependencies
* Python 2.x or Python 3.x
* Node.js
* Pip
* Flask
* BeautifulSoup4

But [requirements.txt](../requirements.txt) currently list many more dependencies.

This repo only contains [two Python scripts](https://github.com/fossasia/query-server/search?l=python) and a quick read of them says that they use:
* `server.py`: dicttoxml, flask, and pymongo
* `scraper.py`: requests, BeautifulSoup4

Could the following dependencies be safely removed from `requirements.txt`? 
```
coverage>=4.3.4  # could be pip installed in .travis.yml but not shipped in production
coveralls>=1.1  # could be pip installed in .travis.yml but not shipped in production
feedgen>=0.5.1
futures>=3.0.5
html5lib>=0.9999999
Jinja2>=2.9.5
librabbitmq>=1.5.1
mechanize>=0.2.5
pytest>=3.0.6  # there are no tests in the repo
pytest-cov>=2.4.0  # no pytest means no pytest-cov?
webencodings>=0.5
```

**Comment by cclauss** [comment]
html5lib should remain in requirements.txt because it is used by bs4.
* https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser

**Comment by ParthS007** [comment]
Is this issue still open ?

**Comment by bhaveshAn** [comment]
> Python 2.x or Python 3.x
    Node.js
    Pip
    Flask
    BeautifulSoup4

From these we all mean is the core modules.

> coverage>=4.3.4  # could be pip installed in .travis.yml but not shipped in production
coveralls>=1.1  # could be pip installed in .travis.yml but not shipped in production

I agree.

> pytest>=3.0.6  # there are no tests in the repo
pytest-cov>=2.4.0  # no pytest means no pytest-cov?

Now it has...
