### ISSUE TITLE
queries are not being added to database

### ISSUE THREAD

**Issue by treeJoker** [fossasia/query-server#134]
The "things" being searched are not added to the database..........

<img width="611" alt="screen shot 2017-09-11 at 8 14 42 pm" src="https://user-images.githubusercontent.com/22785584/30280670-fc3011fa-972d-11e7-8f3a-7ed9428f1346.png">

the condition inside this if is wrong.

<img width="561" alt="screen shot 2017-09-11 at 8 17 56 pm" src="https://user-images.githubusercontent.com/22785584/30280933-a391ec3e-972e-11e7-8bbd-2af416430821.png">

in the above screen shot the databases are not actually made since the mongoDB doesn't create a database until and unless something is inserted to it...........

 i would like to update the code so that it starts adding the searched queries to database

**Comment by ParthS007** [comment]
@treeJoker Please open a new Issue and Explain more in detail.
