### ISSUE TITLE
add a youtube support

### ISSUE THREAD

**Issue by treeJoker** [fossasia/query-server#139]
this would be an enhancement to the existing project

**Comment by Pk13055** [comment]
Working on Quora right now, will add YouTube once I'm done with that.

**Comment by treeJoker** [comment]
Buddy you focus on quora  I'll manage the youtube one

**Comment by Pk13055** [comment]
Sure!

**Comment by Pk13055** [comment]
What's the status? @treeJoker

**Comment by treeJoker** [comment]
buddy I am working on it but since my exams are going on the process has
become somewhat slow

**Comment by bhaveshAn** [comment]
@mariobehling Please close this in relation to #291
