### ISSUE TITLE
TypeError on query-server.herokuapp.com

### ISSUE THREAD

**Issue by AnshulMalik** [fossasia/query-server#140]
I used this query: https://query-server.herokuapp.com/api/v1/search/google?query=anshul&format=json&num=10

And this is what I got :

![queryoffline](https://user-images.githubusercontent.com/7821757/30265721-a77acaca-96fa-11e7-93ce-0e4615a9effd.png)

**Comment by gabru-md** [comment]
Do you get TypeError with all the Search Engines?
Or is it specifically an issue with Google Search?

**Comment by AnshulMalik** [comment]
It's specific to google search @gabru-md

**Comment by gabru-md** [comment]
@AnshulMalik ,
I ran the code on my machine locally and found out that it was caused when the server returned a 500 response.
A 500 response is a response where there is generally an `internal_server_error`.
Try running the following code if you want to know about any `status_codes` :

```python
>> import requests as req
>> req.status_codes._status[500] # 200,304,etc
"('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97')"
```
It happened to me while I was working on it too. Took me a lot of time but found out eventually!
:D

**Comment by gabru-md** [comment]
Well I've figured out a way to handle errors. This happens because of Google Server giving a 500 code response. I'll be sending a PR for the same soon.
PS :@mariobehling

**Comment by AnshulMalik** [comment]
Closing considering #197
