### ISSUE TITLE
librabbitmq contains at least one Python 3 syntax error

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#147]
The version of librabbitmq that this project is using contains at least one Python 3 syntax error.

See: https://github.com/celery/librabbitmq/pull/99

https://travis-ci.org/fossasia/query-server/jobs/275757559#L479
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eiupkwho/librabbitmq/setup.py", line 191
        except Exception, exc:
                        ^
    SyntaxError: invalid syntax
```

**Comment by cclauss** [comment]
> @fossasia-bot fossasia-bot bot added the has-PR label just now

The PR above refers to this issue but it does not fix or resolve this issue.

**Comment by Pk13055** [comment]
@mariobehling Please review.

**Comment by Pk13055** [comment]
@cclauss Do we need librabbitmq in the first place? Looking at the dependencies, it seems that the import is unnecessary? (contrary to #126)
