### ISSUE TITLE
Page not responsive

### ISSUE THREAD

**Issue by sounak98** [fossasia/query-server#150]
The page becomes unusable in smaller screen sizes

![screen shot 2017-09-17 at 11 50 21 am](https://user-images.githubusercontent.com/22390515/30518543-88c86bca-9b9e-11e7-9e55-eee9be829e67.png)

**Comment by sounak98** [comment]
I'd like to work on this.

**Comment by Pk13055** [comment]
@sounak98 Have you pushed yet?

**Comment by Pk13055** [comment]
Are you working on this? @sounak98

**Comment by sakshampatni02** [comment]
I like to Work on It

**Comment by vaibhavsingh97** [comment]
Closing as #167 fix this issue
