### ISSUE TITLE
Number of queries fetched from duckduckgo is not equal to the num value

### ISSUE THREAD

**Issue by shashank-sharma** [fossasia/query-server#154]
![screenshot from 2017-09-19 13-33-57](https://user-images.githubusercontent.com/9320644/30581847-38270882-9d3f-11e7-8b7c-2d6b9f61952e.png)

As shown in image even if the value of num is set to 10 we are getting 30 results.
URL: http://0.0.0.0:7001/api/v1/search/duckduckgo?query=fossasia&format=json&num=10
Issue with Duckduckgo search engine only. For rest it's working fine.

**Comment by shashank-sharma** [comment]
This issue is not that tough, but I would like to work on this and fix it.

**Comment by gabru-md** [comment]
Yes i know this.
When i developed this "num" parameter I was not able to make it for duckduckgo because they have infinite scroll search. 
Therefore the num feature does not work for duckduckgo.  If you would like to make it possible please go ahead.
:+1:
