### ISSUE TITLE
Write Tests

### ISSUE THREAD

**Issue by AnshulMalik** [fossasia/query-server#159]
We don't have any tests at the moment and would love to test our scrapers.

Let's discuss the choice of tester. 
- Unittest https://docs.python.org/2/library/unittest.html

**Comment by vaibhavsingh97** [comment]
@AnshulMalik I am interested to write test cases for this project 😄

**Comment by Pk13055** [comment]
How about [`pytest`](https://docs.pytest.org/en/latest/)? Given the small size of the project and relatively easy tests, it would be easier to use pytest.

**Comment by AnshulMalik** [comment]
@Pk13055 , Yeah, it seems like a good choice

**Comment by Pk13055** [comment]
However, can we wait for the Python 3 port (#152)  to get merged? It'll be easier to be on a specific standard, rather than try supporting tests across various Pythons.

**Comment by AnshulMalik** [comment]
Is it so, that tests will depend on the python version? Unit testing should be simple

**Comment by vaibhavsingh97** [comment]
@AnshulMalik It supports python 2 too
![image](https://user-images.githubusercontent.com/8705386/30758096-8f172216-9fc0-11e7-8144-447bdbf35a7c.png)

**Comment by vaibhavsingh97** [comment]
@AnshulMalik Can i work on this?

**Comment by Pk13055** [comment]
@vaibhavsingh97, let us wait for the Python 3 port to get merged before adding this. Also, tests would be a comprehensive feature which multiple people can work on. It would make no sense to have one person implement all. I will add an issue with the relevant tests, and you can pick any one part from the same. Sounds good?

**Comment by vaibhavsingh97** [comment]
@Pk13055 yeah I know !! Perfect

**Comment by cclauss** [comment]
I believe we should _never_ wait before writing tests.  Test early and test often.  We want tests to pass on both Python 2 and Python 3.  Travis is currently running both in parallel driven by .travis.yml but we currently have Python 3 in allow_failures mode.  We should remove allow_failures after #192 and #193 are merged.

**Comment by AnshulMalik** [comment]
@vaibhavsingh97 @Pk13055 Are you working on this ?

**Comment by Pk13055** [comment]
Yes

**Comment by vaibhavsingh97** [comment]
@Pk13055 is working, so i am waiting for him. Will add my input after his PR will merge

**Comment by cclauss** [comment]
Like I was saying...  Test early and test often.
* https://travis-ci.org/fossasia/query-server/jobs/280955327#L573

**Comment by AnshulMalik** [comment]
@cclauss #214 should fix that, my bad
