### ISSUE TITLE
Responsiveness of website

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/query-server#160]
**Current Behaviour:**
As of now, there is no/less responsiveness as in mobile mode searchbox disappears, and other buttons behaves abnormally.
![image](https://user-images.githubusercontent.com/8705386/30713275-549b463e-9efe-11e7-8102-c3e2f53b22e8.png)
![image](https://user-images.githubusercontent.com/8705386/30713304-6bd1c134-9efe-11e7-98fd-d6b12efc06c7.png)
![image](https://user-images.githubusercontent.com/8705386/30713313-71e80eb6-9efe-11e7-9edd-d18ccf4cece8.png)
![image](https://user-images.githubusercontent.com/8705386/30713322-790a901a-9efe-11e7-9e84-42f5bb1cd603.png)

**Expected Behaviour:**
Website should adapt to various screen sizes

**I am interseted in working on this issue**

**Comment by shashank-sharma** [comment]
Same as #150 issue.

**Comment by Pk13055** [comment]
@vaibhavsingh97 Please close this issue, and reference #150 in your PR.

**Comment by vaibhavsingh97** [comment]
@Pk13055 Sure 😄

**Comment by vaibhavsingh97** [comment]
Closing as #167 fix this issue
