### ISSUE TITLE
Migration of Bootstrap v3 to Bootstrap v4

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/query-server#161]
**Need of migration:**
- New 5 tier grid system for smaller screens
Bootstrap has a sophisticated responsive grid system that allows developers to target devices with different viewports. Bootstrap 3 currently has 4 grid classes for columns, .col-xs-XX for mobile phones, .col-sm-XX for tablets, .col-md-XX for desktops, and .col-lg-XX for larger desktops. Bootstrap 4 will enhance the grid system with a fifth one that will facilitate developers to target smaller devices under 480px viewport width.

- Relative CSS units
 Instead of pixels, the new major release will use REMs and EMs that make it possible to implement responsive typography on Bootstrap sites. This will also increase readability, and make sites more accessible for disabled users.

- Bootstrap cards
Introduced new UI components called cards. Cards will replace the former wells, thumbnails and panels, and will provide users with a more streamlined workflow.

- Flexbox support
Bootstrap 4 makes it possible to take leverage of CSS3’s Flexbox Layout and makes use of the float and display CSS properties to implement a fluid layout.

- All the JavaScript plugins have been rewritten to support ES6. This means you have better plugin support in Bootstrap 4 and can take advantage of the new ES6 features

Benefit: Overall UI improvements + Responsiveness

**I want to work on this issue**

**Comment by Pk13055** [comment]
I don't see this as a necessity. The query server is essentially meant to be a JSON API, and the frontend isn't _as_ important as that for other projects. However, given the one page nature of the application, this wouldn't be such a difficult upgrade and probably won't lead to anything breaking. What say, @mariobehling?

**Comment by AnshulMalik** [comment]
I don't see much benefit of migrating, since we don't need those features yet, query-server is to provide API, and frontend is decent. Bootstrap3 can suite our needs and I think migrating is an overhead.

**Comment by vaibhavsingh97** [comment]
@AnshulMalik Closing since i also see no necessity now 👍 
@Pk13055 Thanks for your input though
