### ISSUE TITLE
Adding Dailymotion support.

### ISSUE THREAD

**Issue by Kanav-7** [fossasia/query-server#163]
I am currently working on this issue

**Comment by bhaveshAn** [comment]
@Kanav-7 Are you done with it. Please let me know. Thanks!

**Comment by bhaveshAn** [comment]
Any update @Kanav-7 ??

**Comment by jajodiaraghav** [comment]
@Kanav-7 Are you working on this or can I take it?

**Comment by jajodiaraghav** [comment]
Claiming this since not update was made 🚀
