### ISSUE TITLE
Showing Internal Server Error when tried to search on Query Server

### ISSUE THREAD

**Issue by ms10398** [fossasia/query-server#166]
Query Server responded with 500 Internal Server Error
Update: Error showing only when searching using Google

![screenshot from 2017-09-23 02-41-14](https://user-images.githubusercontent.com/26259547/30764512-ee7077ba-a008-11e7-996d-8c2dcd55582c.png)

**Comment by vaibhavsingh97** [comment]
@ms10398 It's a known bug and it only appears when you Google it.

**Comment by ms10398** [comment]
@vaibhavsingh97 Okay I didnt knew that.
Thank you

**Comment by vaibhavsingh97** [comment]
@ms10398 Why you closed the issue? We need to solve that 😄 
I am interested in working on this 😬

**Comment by ms10398** [comment]
Sure Go Ahead

**Comment by vaibhavsingh97** [comment]
@ms10398 Created PR, please review
