### ISSUE TITLE
Intgration of Hound CI

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/query-server#174]
- Bot comments on style violations in GitHub pull requests, allowing us to better review and maintain a clean codebase.

**Comment by vaibhavsingh97** [comment]
I am claiming this

**Comment by cclauss** [comment]
Travis is already doing this but we have it working in __--exit-zero__ mode.  All we have to do is remove __--exit_zero__ in .travis.yml and we have the same level of functionality.

https://travis-ci.org/fossasia/query-server/jobs/279784188#L661

**Comment by cclauss** [comment]
Now that I have seen hound in action, I like it and recognize that it adds nice UI to the PR submission process but we will need better documentation on how to comply with the perfect PR policy once hound has pointed out a violation on a PR.
