### ISSUE TITLE
Adding AOL support

### ISSUE THREAD

**Issue by S2606** [fossasia/query-server#183]
Adding enhancement to the project.

**Would you like to work on this?**
yes

**Comment by S2606** [comment]
@bhaveshAn  At least you could have asked me before working???

**Comment by bhaveshAn** [comment]
@S2606 since, this issue haven't recieved any conversation from more than 12 days, so thought you might have dropped the idea. 
BTW, apologies, could you please work on [GigaBlast](http://www.gigablast.com/) it''s the same type of search engine.

**Comment by mariobehling** [comment]
According to the resources I found AOL uses Google as a search provider. Therefore we don't need it as another search engine that is already covered by the original.
