### ISSUE TITLE
Application error on website

### ISSUE THREAD

**Issue by aviaryan** [fossasia/query-server#184]
I see this error when I open the website https://query-server.herokuapp.com/. 

![screen shot 2017-09-24 at 7 59 38 pm](https://user-images.githubusercontent.com/4047597/30783584-edcdede6-a162-11e7-9f65-1785bb2054f0.png)

**Comment by vaibhavsingh97** [comment]
@aviaryan Do you want to work on this?

**Comment by aviaryan** [comment]
No, sorry I don't have the time to work on this atm.

**Comment by S2606** [comment]
@aviaryan i would like to work on this

**Comment by shashank-sharma** [comment]
I guess it is python3 support error. Even I was trying to push my code in Heroku server but it was keep on failing.

**Comment by cclauss** [comment]
HINT: When I push, I get messages like:
* Heroku: app.json is not valid; __scripts: must be of object type__

Perhaps look at https://devcenter.heroku.com/articles/app-json-schema#scripts

**Comment by bhaveshAn** [comment]
@S2606 have you worked on this ?

**Comment by AnshulMalik** [comment]
Our project uses both python and node, so
- We need a buildpack which supports both of these
- Add a `runtime.txt` file telling which version of python to use

And after that we'll see what happens

**Comment by S2606** [comment]
@bhaveshAn I am working on it

**Comment by cclauss** [comment]
runtime.txt can be 2.7.14 as of today... https://github.com/heroku/heroku-buildpack-python/pull/475

**Comment by cclauss** [comment]
With #204 merged, can someone please restart the server?
