### ISSUE TITLE
Heroku Deployment not working

### ISSUE THREAD

**Issue by ms10398** [fossasia/query-server#190]
When visiting this link[https://query-server.herokuapp.com/] 
It shows application error 

**Screenshot is below**

![screenshot from 2017-09-25 11-21-30](https://user-images.githubusercontent.com/26259547/30794100-e74f519a-a1e3-11e7-87f3-8746141c7b0c.png)

**Comment by aviaryan** [comment]
Duplicate of #184

**Comment by vaibhavsingh97** [comment]
I am claiming issue this issue

**Comment by cclauss** [comment]
Duplicate of #184 ?

**Comment by bhaveshAn** [comment]
I would like to work on this issue. May I ?

**Comment by ms10398** [comment]
I think there is already @vaibhavsingh97 working on it

**Comment by bhaveshAn** [comment]
Please close this one !
