### ISSUE TITLE
'desc' is missing from ask.com

### ISSUE THREAD

**Issue by gabru-md** [fossasia/query-server#196]
The `description` tag is missing from `ask.com` search results.
An Image of current search results.

![cr](https://user-images.githubusercontent.com/25414121/30843728-01635f6e-a283-11e7-9e15-cf96dbbdd9c5.png)

Modified Behaviour:
Should produce `desc` like all the other search engines.

**Yes** i would like to work on this bug.

**Comment by bhaveshAn** [comment]
@gabru-md please let me know are you working on this. If not, I want to submit the PR. Thanks !!

**Comment by gabru-md** [comment]
Sorry I was ill and could not do it. Will do it asap and send a PR. 
Sorry for any inconvenience
