### ISSUE TITLE
Use Duckduckgo instead of google

### ISSUE THREAD

**Issue by nikhilkumarsingh** [fossasia/query-server#2]
There are several reasons to support duckduckgo instead of google for your query server:
- As of now, there is no python 3 version of Mechanize library.
- Dependency of mechanize library is removed if we try to scrape the duckduckgo search results.
- Your IP is more prone to getting blocked by google as compared to duckduckgo if you exceed the no. of permissible requests.

So, should I make a pull request with a modified version of query search using duckduckgo?

**Comment by enigmaeth** [comment]
Okay. Go on!

**Comment by mariobehling** [comment]
@nikhilkumarsingh Thank you. It would be great to get support for both. We definitely need to keep the support for Google.

**Comment by mariobehling** [comment]
This is also a follow up to https://github.com/fossasia/searss/issues/6#issuecomment-267818630

**Comment by djmgit** [comment]
@mariobehling should the user be provided with an option to choose between google and duckduckgo before providing the search string or the search result should be a combination of the results of google and duckduckgo without letting the user bother about the search engine ?

**Comment by nikhilkumarsingh** [comment]
Since top search results for any query are almost same on both engines, it does not make any sense to use a combination of both results.
User must be given choice to select the search engine in my opinion.

**Comment by djmgit** [comment]
@nikhilkumarsingh Okay, I will be sending a PR soon

**Comment by nikhilkumarsingh** [comment]
@djmgit I am already using my patch from [searss](https://github.com/fossasia/searss) and have made PR #8 .

**Comment by djmgit** [comment]
@nikhilkumarsingh okay :)
