### ISSUE TITLE
Add support for Yandex

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#201]
Adding enhancement of [WebCrawler](http://www.webcrawler.com/), [WolframAlpha](http://www.wolframalpha.com/) and [Yandex](https://www.yandex.com/) to the project.

**Would you like to work on this?**
yes

**Comment by AnshulMalik** [comment]
What exactly are you talking about here?

**Comment by bhaveshAn** [comment]
@AnshulMalik I would like to add `WebCrawler`, `WolframAlpha` and `Yandex` related interfaces in this repo same as it already has Google, Bing etc
Got it ?

**Comment by mariobehling** [comment]
Yandex sounds good. Webcrawler is a meta search itself and probably not so relevant therefore. 

I am not sure about Wolfram Alpha. It is not a traditional search engine.

**Comment by mariobehling** [comment]
What about Chinese search engines? Baidu?

**Comment by shashank-sharma** [comment]
@mariobehling I have opened Baidu issue and I would like to work on it #202

**Comment by bhaveshAn** [comment]
@mariobehling Thanks. I will work on Yandex. Btw, if you have any suggestions other than Baidu, I will love to hear that too !
