### ISSUE TITLE
Addition of  CSV support

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/query-server#210]
- [x] Feature Request

#### Current Behaviour
As of now, result supports only JSON, XML.

#### Expected Behaviour
Result should support JSN, XML, CSV 

**Yes, I would like to work on this issue**

**Comment by rupav** [comment]
Hi @vaibhavsingh97 , are you working on this?
If not, can I work on it?

**Comment by vaibhavsingh97** [comment]
@rupav yes!

**Comment by dgarvit** [comment]
@rupav are you still working on it? If not, can I work on this?

**Comment by rupav** [comment]
@dgarvit I am not assigned to this task, please ask @vaibhavsingh97 for the same. :)

**Comment by vaibhavsingh97** [comment]
@rupav I said, yes for the last question you asked 😆 . Now, we have one PR already 😄

**Comment by rupav** [comment]
Oh, I though you said yes that you are working on it. Misinterpreted that 😅. Sorry
