### ISSUE TITLE
Internal server error [Status code: 500]

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#215]
After going through the installation steps (including mongodb-org ). I find 

![screenshot from 2017-09-28 19-58-34](https://user-images.githubusercontent.com/22936570/30973021-9dffcec8-a45b-11e7-9e37-e1579108c884.png)

The logs are:

> * Running on http://0.0.0.0:7001/ (Press CTRL+C to quit)
* Restarting with stat
* Debugger is active!
* Debugger PIN: 275-635-326
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/bower_components/prismjs/themes/prism.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/bower_components/jquery/dist/jquery.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/bower_components/prismjs/prism.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/images/forkme_right_green_007200.png HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/images/google_icon.png HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/images/bing_icon.ico HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/images/duckduckgo_icon.png HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/images/yahoo_icon.ico HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/images/ask_icon.ico HTTP/1.1" 304 -
127.0.0.1 - - [28/Sep/2017 20:12:27] "GET /static/images/ripple.gif HTTP/1.1" 304 -
Invalid URL '': No schema supplied. Perhaps you meant http://?
127.0.0.1 - - [28/Sep/2017 20:12:33] "GET /api/v1/search/google?query=fossasia&format=json&num=10 HTTP/1.1" 200 -

**Yes , I would like to work on this issue**

**Comment by AnshulMalik** [comment]
Hey @bhaveshAn, Sorry again, but https://github.com/fossasia/query-server/pull/214 resolves the issue :P
