### ISSUE TITLE
No query with duckduckgo

### ISSUE THREAD

**Issue by sinAshish** [fossasia/query-server#221]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
No query results are produced with duckduckgo
**Expected behavior:**
It should produce results as  in case of Google and Bing.

**Steps to reproduce:**

**Comment by sayak119** [comment]
![screenshot from 2017-10-02 17-35-15](https://user-images.githubusercontent.com/28414920/31076528-153281d2-a76a-11e7-8110-8f8bf27a1615.png)

Duckduckgo is showing results

**Comment by shashank-sharma** [comment]
This should be closed as everything is working fine.

**Comment by sinAshish** [comment]
The results were not showing on my system.
