### ISSUE TITLE
Scrapers should implement absolute_import

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#226]
The current scrapers will not work on Python 3 because they do relative importing.  The problem is shown here: https://travis-ci.org/fossasia/query-server/jobs/282968780#L558

The solution is to:
1. from __future__ import absolute_import
2. from .generalized import Scraper  # add the dot (.)
(See https://github.com/fossasia/query-server/pull/225/files#diff-ae74241666286cc647595b08d2de8ac2 for an example)

Without item 2 above, Python 3 will get lost.

**Comment by bhaveshAn** [comment]
@cclauss Since we are using `python` command at https://github.com/fossasia/query-server/blob/master/Procfile so I don't think we have to enforcing the application to work on `python3` 
Thoughts ??

**Comment by cclauss** [comment]
On your local machine:
* make a new directory
* cd into that directory
* type: `python3 -m venv . ; . bin/activate`  # you have activated a Python 3 virtualenv
* type `python -V`  # Python 3.6.3

All of these Cloud Foundry providers like Heroku, Bluemix put your stuff into a virtualenv so runtime.txt should determine if "Python" is Python 2 or Python 3.  https://github.com/heroku/heroku-buildpack-python/graphs/contributors

The Travis tests run in virtualenvs too so you can see that when we use python and pip there, they are controlled by the way the virtualenv is set up.
