### ISSUE TITLE
Should we use the adapter pattern and dynaimic loading of scrapers?

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#233]
There are several recent PRs to add new scrapers to the system and each one needs to touch ~ four different files.  Will there be a lot more scrapers to add or are we almost done?  Would it be better to shift to using the _adapter pattern_ for adding new scrapers?  This would:
1. Make adding new scrapers easier by focusing the changes into fewer files
2. Make debugging and testing of scrapers easier
3. Allow for dynamic loading so that users could add their own scrapers and the system can detect them at startup

https://github.com/LazoCoder/Pokemon-Terminal/tree/master/pokemonterminal/adapter is an example of applying the adapter pattern to adding terminal drivers.

If there are a some votes of interest then I would be interested to co-develop this with someone so please let me know if you are interested to co-develop.

**Comment by bhaveshAn** [comment]
@cclauss I am ready to co-develop it with you. That is a good idea.

**Comment by cclauss** [comment]
Wow...  It has been a while.  But I am still up for collaboration on this.
