### ISSUE TITLE
Adding Gigablast suppport

### ISSUE THREAD

**Issue by S2606** [fossasia/query-server#234]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Would you like to work on this?
Yes**

**Comment by vaibhavsingh97** [comment]
@S2606 Are you working on this?

**Comment by S2606** [comment]
@vaibhavsingh97 Yes i am working on this

**Comment by bhaveshAn** [comment]
@S2606 Are you done with it. Please let me know. Thanks!

**Comment by bhaveshAn** [comment]
@vaibhavsingh97 @starlord1311 @ParthS007 Anyone of you like to work on this ?

**Comment by starlord1311** [comment]
I would like to work on this

**Comment by starlord1311** [comment]
What am I supposed to do?

**Comment by rupav** [comment]
@starlord1311 you can refer [yandex support](https://github.com/fossasia/query-server/pull/229) for e.g., and other similar closed PRs to take help.

**Comment by mariobehling** [comment]
Low priority. This is currently not needed.
