### ISSUE TITLE
Add support for Exalead 

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#236]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently no support for [Lycos](http://search.lycos.com/) , [Qwant](https://www.qwant.com/web), [Exalead](http://www.exalead.com/search/web), [Teoma](https://www.teoma.com/web), [Ecosia](https://www.ecosia.org/)

**Expected behavior:**

Adding support for [Lycos](http://search.lycos.com/), [Qwant](https://www.qwant.com/web), [Exalead](http://www.exalead.com/search/web), [Teoma](https://www.teoma.com/web), [Ecosia](https://www.ecosia.org/)

**Steps to reproduce:**

**Would you like to work on this Issue**
Yes, I would like to work on this.

**Comment by niranjan94** [comment]
@bhaveshAn remove Ecosia please. It is powered by Bing. Since we already support bing, this isn't really needed.
