### ISSUE TITLE
404 error on clicking Maintainer

### ISSUE THREAD

**Issue by rupav** [fossasia/query-server#248]
https://github.com/fossasia/query-server/blob/232e6c2f08f9e8a1e589c64b28bd5975a6442bf8/app/templates/index.html#L105

[https://query-server.herokuapp.com/nikhilrayaprolu](url)

![2017-10-10 2](https://user-images.githubusercontent.com/20624380/31397518-df40b486-ae03-11e7-8693-d66c9d7b2d25.png)

**Expected Behaviour:**
Maintainer's github profile.

**Would you like to work?**
Yes.

**Comment by vaibhavsingh97** [comment]
@rupav Please fix it! It's mine mistake 😅

**Comment by rupav** [comment]
Hi @vaibhavsingh97 , I tried it on my forked repo, I changed in index.html . But I cant see changes in https://query-server.herokuapp.com.
Can you tell me what can be the reason?
Do I need to change in some other file too, to get the changes reflected on the herokuapp.

**Comment by vaibhavsingh97** [comment]
@rupav It's deployed on heroku and your changes will not reflect on that until your PR will merged into master/development.
