### ISSUE TITLE
Add Codecov CI

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#251]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

Add Codecov Continuous Integration
**Steps to reproduce:**
**Would you like to work on this issue**
Yes, I would like to work on this.

**Comment by cclauss** [comment]
Codecov does not like the assert statements that pytest does like.

**Comment by starlord1311** [comment]
i am new to this. what should i do for this issue?

**Comment by bhaveshAn** [comment]
@starlord1311 Just do some research on Codecov. Check some repos on github which uses Codecov.
Trust me, its pretty easy :smiley:

**Comment by bhaveshAn** [comment]
@mariobehling Please close this in regard to #288 . Thanks !!
