### ISSUE TITLE
Increase --max-line-length in travis.yml

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#252]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
Apologies, earlier changed the `--max-line-length` for HoundCI and not for Travis CI. This issue is in regards of same in Travis.
 
**Current behavior:**

Currently, --max-line-length = 85 in .travis.yml is responsible for build failing at #240 
**Expected behavior:**

Changing --max-line-length = 85 to --max-line-length = 150 in .travis.yml will pass the build and in future too.
**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Comment by Pk13055** [comment]
Shouldn't max line length be set to 79 as per PEP standards?
