### ISSUE TITLE
Ask search engine is crashing the web app

### ISSUE THREAD

**Issue by shashank-sharma** [fossasia/query-server#258]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Type any query let us say fossasia and choose count to 100 or 80+ and then you will notice that the web app will crash and then it will no longer work. It is happening because the result keeps on going and achieve infinite loop.

When ask.com gets to https://www.ask.com/web?q=fossasia&page=7 then at page 7 you will get no result so with no result nothing will append and it keeps on going to 8, 9, 10 with no result and then it becomes an infinite loop. It cannot be fixed except we can give exception to this search engine by showing or indicating an error message.
**Expected behavior:**

It should give proper 100 results

![screenshot from 2017-10-20 11-55-17](https://user-images.githubusercontent.com/9320644/31807747-9f5259ec-b58d-11e7-8e75-f8d7932d8339.png)
![screenshot from 2017-10-20 11-54-48](https://user-images.githubusercontent.com/9320644/31807757-a72cead8-b58d-11e7-85c1-de16eda3e324.png)

**Comment by rupav** [comment]
Can I work on this ?

**Comment by shashank-sharma** [comment]
Sure, go for it :+1:
