### ISSUE TITLE
Add support for Looksmart search

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#259]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

Add support for [LookSmart](http://www.looksmart.com/)

**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Comment by srisankethu** [comment]
Yes, I would like to work on this issue

**Comment by jajodiaraghav** [comment]
Claiming this since no update has been made for past 2 weeks 🚀

**Comment by bhaveshAn** [comment]
Please don't work on this issue. Looksmart is a meta search engine. Hence closing it.
