### ISSUE TITLE
Add Dogpile support

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#260]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

Add support for [Dogpile](http://www.dogpile.com/) 

**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Comment by mariobehling** [comment]
Dogpile is a meta search engine itself and provides results from engines we already cover.

> Dogpile is a metasearch engine for information on the World Wide Web that fetches results from Google, Yahoo!, and Yandex, and includes results from several other popular search engines

Therefore closing it.
