### ISSUE TITLE
Add Excite support

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#262]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

Add support for [Excite](http://www.excite.com/)

**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Comment by srisankethu** [comment]
Yes, I would like to work on this issue

**Comment by raju249** [comment]
@bhaveshAn @srisankethu ,
Is anyone of you working on this issue ?

**Comment by ParthS007** [comment]
@raju249 I am working on this Issue but I have my exams this week, will make PR as soon my exams are over.

**Comment by bhaveshAn** [comment]
@raju249 I will send the PR in one day. Or if not possible then you can work on this as you claimed before @ParthS007

**Comment by raju249** [comment]
Sure @ParthS007.
Go ahead and good luck with exams 😊.

Np @bhaveshAn please take your time.
Just make sure that both of you are not using your time on same issue. 😉

**Comment by ParthS007** [comment]
working on it :+1:

**Comment by raju249** [comment]
@ParthS007 Excite redirects you to captcha page.
Just try it and you will see :sweat_smile: 
Let me know if you have any other work around if you are redirected to captcha page

**Comment by ParthS007** [comment]
closing it as no more search engine are required
