### ISSUE TITLE
Human readibility is low

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/query-server#265]
**Actual Behaviour:**
Code is not human readable
https://github.com/fossasia/query-server/blob/e095c978b0db02973d9f47bb74fc28dcaf31992b/app/server.py#L91-L95

**Expected Behaviour:**
Should be human readable

**Open to claim**

**Comment by cclauss** [comment]
autopep8 or yapf will do the right thing...

**Comment by cclauss** [comment]
Should this issue be closed?

**Comment by cclauss** [comment]
Should this issue be closed?

**Comment by ParthS007** [comment]
@vaibhavsingh97  Please update 👍

**Comment by vaibhavsingh97** [comment]
@ParthS007 Let beginner should do it.

**Comment by cclauss** [comment]
Do what exactly?  The code mentioned above is already cleaned up.  Where are other examples in the current codebase that need to be cleaned up?

**Comment by nalawadepiyush** [comment]
@vaibhavsingh97  is this issue active or closed, if active i can take up and clean up the code with autopep8

**Comment by vaibhavsingh97** [comment]
@nalawadepiyush Sure, Please send PR 👍

**Comment by DevSingh1101** [comment]
@vaibhavsingh97 can I take up this issue?

**Comment by cclauss** [comment]
This issue can be closed as the problem has already been fixed.
