### ISSUE TITLE
Bluemix deploy failure

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#270]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

Click "Deploy to Bluemix" button...  See #255
```
Uploading query-server-20171024223053555...
Uploading app files from: /home/pipeline/d4bdf7300-265f-463a-90fd1-c289db0445b20
Uploading 86.4K, 52 files
                       
Done uploading
OK
FAILED
Could not find service todo-mongo-db to bind to query-server-20171024223053555

Finished: FAILED
```

**Expected behavior:**

Running app

**Steps to reproduce:**
Click "Deploy to Bluemix" button...

**Comment by raju249** [comment]
Seems like Bluemix removed mongodb from their service offering.
Checkout https://www.ibm.com/blogs/bluemix/2015/10/mongodb-removal/

**Comment by raju249** [comment]
They have other alternatives though
