### ISSUE TITLE
Yandex search uses Yahoo, not Yandex

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#271]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

The Yandex button runs a Yahoo search.

**Expected behavior:**

The Yandex button runs a Yandex search.

**Steps to reproduce:**
Enter a search term and click the Yandex button.

**Comment by shashank-sharma** [comment]
Seems like that PR was not reviewed correctly.
![screenshot from 2017-10-25 16-52-10](https://user-images.githubusercontent.com/9320644/31996146-eef4636c-b9a4-11e7-9f23-8a8b653ea509.png)

**Comment by gabru-md** [comment]
Will like to work on this.

**Comment by cclauss** [comment]
@gabru-md Have you made any progress on this one?  When I enable this scraper (by moving Yahoo out of the way) it does not seem to return results.  Should we just drop support for Yandex?

**Comment by gabru-md** [comment]
Sorry @cclauss i was a bit busy last 30 days due to my exams. I'll work on this and notify you in a day.

**Comment by raju249** [comment]
Claiming this due to inactivity

**Comment by raju249** [comment]
Although yandex redirected me to captcha page when I tried locally.

**Comment by cclauss** [comment]
Do we drop support for Yandex?
