### ISSUE TITLE
Improper search engine names used

### ISSUE THREAD

**Issue by shashank-sharma** [fossasia/query-server#273]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

API url are mostly used to make values human readable like if we want to search google search engine then we can type google but right now baidu is represented as ubaidu which is not good.

https://query-server.herokuapp.com/api/v1/search/ubaidu?query=fossasia&format=json&num=10
**Expected behavior:**

It should look like 
https://query-server.herokuapp.com/api/v1/search/baidu?query=fossasia&format=json&num=10

**Comment by bhaveshAn** [comment]
> API url are mostly used to make values human readable like if we want to search google search engine then we can type google but right now baidu is represented as ubaidu which is not good.

I think you are contradicting your self, now.
`ubaidu` is used instead of `baidu` . This is because all the search engines are used with unique key in `app/scrapers/__init__.py`.
If baidu was used than [b] was the key  which is already for `bing`
So, now, 
1. g --> google
2. a --> ask
3. d --> duckduckgo
4. b --> bing
5. y --> yahoo
6. u --> baidu as ubaidu

So, it is not a issue. Hence, should be closed.

**Comment by cclauss** [comment]
Why use only the first letter instead of the full name?

**Comment by shashank-sharma** [comment]
Why can't you change the method ? I am talking about the use of api. It should be easy to use. ubaidu doesn't make any sense that's why we need to do something about this so that user can type baidu instead of ubaidu.

**Comment by cclauss** [comment]
@shashank-sharma I agree with you.  #266 changes the Python code so that the Python code uses the whole name and not just the initial letter and that we convert all instances of ubaidu into baidu.

**Comment by raju249** [comment]
Do we really need this ?
@bhaveshAn 
If yes, then I would like to claim this. But this will also mean to update susi and other users about this change.
What you think ?

**Comment by cclauss** [comment]
@raju249 Our README.md says noting about __u__baidu and __t__youtube so it would be good to fix the other apps and this app to align to our API description in our README.md.  There are solutions to this issue in both #327 and #342 so it would be great if you could author a solution that actually gets merged.

**Comment by raju249** [comment]
Sure @cclauss 
But #342 looks like a lot of changes and LGTM. Why don't we merge that then ?

**Comment by cclauss** [comment]
This is not closed.  The current code still rejects baidu, dailymotion, and youtube unless they have the character prepended to them.

**Comment by cclauss** [comment]
This issue is closed?

**Comment by cclauss** [comment]
Can we please close this issue?!?
