### ISSUE TITLE
Ask search engine generating error for some special case

### ISSUE THREAD

**Issue by shashank-sharma** [fossasia/query-server#279]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

type 'a b c d e f' and then you will notice that it will give 500 error

Error is generating because as you can see there are 4 videos in one div and there are no descriptions.
This can be possibly solve by removing description tag from results and show only url and title. 

![screenshot from 2017-10-26 23-33-54](https://user-images.githubusercontent.com/9320644/32069270-400f9026-baa6-11e7-9d7c-ca4614cf0a9d.png)

**Comment by Dragneel7** [comment]
@shashank-sharma Hello, I am new to open source and would like to contribute by resolving the above mentioned issue.Can I take up this issue?

**Comment by shashank-sharma** [comment]
Hi @Dragneel7
Yes, sure you can work on this issue. If you face any problem let me know.

**Comment by gabru-md** [comment]
@shashank-sharma
We should not remove description tag. But could definitely do some error handling to avoid this issue?

**Comment by shashank-sharma** [comment]
@gabru-md I am saying this because there are many search engines which are not viewing description. Either make one standard rule that every search engine must have description or remove from all of them

**Comment by Dragneel7** [comment]
@shashank-sharma  Thank you , I will work my best and contact you if I face any issues.

**Comment by Dragneel7** [comment]
@shashank-sharma "Ask" is giving the same problem for almost every query I tried.
Can you give me example query where it works properly.
![deepinscreenshot_20171030135353](https://user-images.githubusercontent.com/24193342/32161092-5931bfe4-bd7a-11e7-867f-cd764bfdb7a0.png)

**Comment by Dragneel7** [comment]
@shashank-sharma removing the desc from "ask.py" worked. So should we remove it or go for try-catch method.
![deepinscreenshot_20171030140307](https://user-images.githubusercontent.com/24193342/32161387-5b88a14e-bd7b-11e7-87a3-abd345eef889.png)

**Comment by shashank-sharma** [comment]
@Dragneel7 Hi, Yea sure make that PR. And then you can wait for reviews and make changes according to that.
Sorry for such late reply

**Comment by rupav** [comment]
@Dragneel7 are you working on this or can I do it? @shashank-sharma @Dragneel7  what I think we should keep the description, if there isnt any, just return "''".

**Comment by bhaveshAn** [comment]
Yeah :smile: Doing error handling is the best option !!
