### ISSUE TITLE
The hound is asleep -- Please wake him up

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#281]
Usually you should __let sleeping dogs lie__ but this issue is bugging me...

**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

I submit a PR that contains an unused import.  According to #174 and #206 Hound should catch my mistake and allow the error be to fixed before the PR will be accepted.

**Expected behavior:**

Hound does not seem to catch any errors and then Travis finds them.

**Steps to reproduce:**
Submit a PR that has a style violation such as unused import

**Comment by ParthS007** [comment]
I am working on it

**Comment by cclauss** [comment]
@ParthS007 and @niranjan94 How do I get to see Hound in action?  I never get any Hound notifications on my pull requests.  fossasia-bot seems to be very chatty but I never hear from Hound.
