### ISSUE TITLE
The query server does not give an xml output

### ISSUE THREAD

**Issue by mariobehling** [fossasia/query-server#3]
No XML output yet, but it should.

**Comment by nikhilkumarsingh** [comment]
Use html5lib parser instead of html.parser

**Comment by nikhilkumarsingh** [comment]
I think this issue must be closed now...

**Comment by niranjan94** [comment]
@nikhilkumarsingh I don't see how this issue is related to PR #4 ..

**Comment by nikhilkumarsingh** [comment]
@niranjan94 The earlier version used html.parser which was giving errors in parsing the HTML content.
So, I used html5lib as HTML parser. This resolved the issue. :)

**Comment by niranjan94** [comment]
@nikhilkumarsingh I think you misunderstood ... This issue is about the fact that the query server is not providing an **XML Output**. Not related to parsing of webpages.

**Comment by nikhilkumarsingh** [comment]
@niranjan94 Did you mean that the xml output is not getting saved into files?
Check out PR #5. It works for me in all respects.

**Comment by mariobehling** [comment]
@nikhilkumarsingh XML output still not working. The issue is about XML output. If it works for you, please provide an XML sample output that we can see.

**Comment by nikhilkumarsingh** [comment]
Please have a look at this file. This file gets generated using new version : https://github.com/nikhilkumarsingh/query-server/blob/9a735f14af371baf96166409fdf7ad3280225505/data/india.xml

**Comment by enigmaeth** [comment]
@mariobehling The server provides the XML output in the console. Also a file which contains the XML output  is saved with the name of the 'query string', in **query-server/data** folder. I think you weren't able to find the stored files. Please explain the issue in case I misunderstood!

**Comment by rhemon** [comment]
I am also having that problem
when I do a query, not matter what the string is, it turns to 'undefined'
```
Search for >> fossasia
        querying -> undefined
```
also it says this ` saved to file : query-server/data/undefined.xml` but there is no such file in the data folder

**Comment by rhemon** [comment]
the XML file for google search is getting created successfully, but it is not creating when its doing the query with duckduckgo (or bing). I think thats what @mariobehling meant in this issue @enigmaeth

**Comment by rhemon** [comment]
sorry, its working, xml files are created

**Comment by rhemon** [comment]
I think this was problem was with duckduckgo query since it didnt happen properly because of the AttributeError, mentioned in https://github.com/fossasia/query-server/issues/11
The problem should be fixed with https://github.com/fossasia/query-server/pull/13
