### ISSUE TITLE
Add search engine name to the printed parsed output

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#301]
@starlord1311 Would you be interested to work on this one?

**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Current printed output is usually __parsed[{“title”: ...__
**Expected behavior:**

Desired printed output could be __Google parsed: [{“title”: ...__

**Steps to reproduce:**
* Run a Quora search to see the right kind of output.
* Run a Google search to see the wrong kind of output.

https://github.com/fossasia/query-server/blob/master/app/scrapers/quora.py#L21
Does it right and the other search engines should be modified to do things the same way.
https://github.com/fossasia/query-server/blob/master/app/scrapers/google.py#L27

This change would make it easier to find and fix bugs like #271

**Comment by starlord1311** [comment]
yes i would like to take this up.

**Comment by starlord1311** [comment]
can you please tell what i have to do?
