### ISSUE TITLE
Add pytests that simulate external API calls

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#302]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] test request

**Current behavior:**

External requests like https://query-server.herokuapp.com/api/v1/search/gigablast are not currently tested.
**Expected behavior:**

Add tests to the Travis CI process that make external API calls to both valid and invalid scraper names.
**Steps to reproduce:**

**Comment by shaddygarg** [comment]
Hello, I would like to work upon this. Can I take up this issue?

**Comment by cclauss** [comment]
Go for it!

**Comment by shaddygarg** [comment]
@cclauss I was thinking of using requests to simulate the API calls. Should I proceed with it?

**Comment by cclauss** [comment]
Yes.

**Comment by shaddygarg** [comment]
Please have a look at the PR!
