### ISSUE TITLE
Add Medium support

### ISSUE THREAD

**Issue by ParthS007** [fossasia/query-server#305]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:*

**Steps to reproduce:**

Yes, I would like to work on this issue

**Comment by starlord1311** [comment]
i would like to work on this issue.

**Comment by ParthS007** [comment]
@starlord1311 I am working on this , you can take any other open issue .

**Comment by bhaveshAn** [comment]
Any update?

**Comment by ParthS007** [comment]
@bhaveshAn  Almost done with it will give a PR by tomorrow.

**Comment by mariobehling** [comment]
Medium is not a search engine. It looks to me that the major search engines are covered and we dont need to add more. Therefore closing it.
