### ISSUE TITLE
Youtube results not equal to num value

### ISSUE THREAD

**Issue by shashank-sharma** [fossasia/query-server#308]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

If we type 'fossasia' and then click on youtube then it is giving more than 10 results for num = 10
**Expected behavior:**
It should give only 10 result

It would be great if any new person would like to take this issue and solve it. :+1:

**Comment by ParthS007** [comment]
@shashank-sharma  I have checked the code, youtube and Quora have to give result without count.

**Comment by shashank-sharma** [comment]
@ParthS007 But this need to be fixed right ? Or we are planning to keep it as it is. Because if we will not change then what's the point of using num=10 or anything like that.

**Comment by starlord1311** [comment]
i would like to take up this issue

**Comment by shashank-sharma** [comment]
@starlord1311 Sure, go ahead

**Comment by bhaveshAn** [comment]
@shashank-sharma Please go through https://github.com/fossasia/query-server/pull/287#issuecomment-340203644 
same is the reason for youtube. 
Hence, can be closed.

**Comment by shashank-sharma** [comment]
@bhaveshAn Don't you think that we should remove those num values because at the end it doesn't make any sense to put that if it is not working for every search engine ? Or make exceptions ?

**Comment by bhaveshAn** [comment]
Nope, I don't think removing num values would be solution for this as 8/10 engines are following it. So definitely not a solution to the problem. (Infact, still I don't thing it as a issue)

**Comment by raju249** [comment]
@bhaveshAn  
Should this issue be closed, I think its resolved after above explanation.
What you think ?
