### ISSUE TITLE
Migration of query server to Scrapy

### ISSUE THREAD

**Issue by ParthS007** [fossasia/query-server#312]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Currently, query server uses Beautiful Soup which is slower as compared to scrapy and requires more code to maintain.

**Expected behavior:**
Scrapy will allow faster gathering of data, as well as rapid development and It's benefit include providing outputs in multiple formats (like JSON, XML, CSV) without writing explicit code for each.
Please go through [Scrapy Documentation](https://scrapy.org/) for more info.

**Comment by ParthS007** [comment]
@mariobehling  @cclauss  @bhaveshAn  Your views ?

**Comment by cclauss** [comment]
* Is performance currently a problem for us?
* What is the license for this software?
* Would this make us reliant on their scrapinghub service?
* Which Python files and which lines in those files would you expect this to change?
* Do you have a sense for how many lines of code we could eliminate with this change?

**Comment by ParthS007** [comment]
- Performance is not the issue but Beautiful Soup cannot scrape all the sites with ease but with scrapy, It will be more convenient.
- Scrapy uses BSD-3-Clause License.
- It can be reliant.
- It changes the code in generalized.py and some other files.
- scrapy will allow more Idiomatic code.

**Comment by shashank-sharma** [comment]
I agree, scrapy is much better than BeautifulSoup and it will be easy to manage code with it. Off course we are talking about spider scraping those sites.

**Comment by cclauss** [comment]
Is there a cost or downside to being reliant on their scrapinghub service?

**Comment by shashank-sharma** [comment]
ScrapingHub service is also great, it gives you 1 free dyno but then after that you need to pay for it. It's not like heroku. You just deploy your spider and then it will run for 24 hours for free user and 7 days for paid one.

**Comment by AnshulMalik** [comment]
I don't feel any need of using scrapy here.

Beautiful soup is fine, and performance isn't an issue here, did you run benchmarks @ParthS007 ?

**Comment by cclauss** [comment]
I agree.  I use Bluemix so free Heroku dynos are of little interest more importantly, I worry about being tied to the ScrapingHub service.

**Comment by bhaveshAn** [comment]
Not really needed

**Comment by cclauss** [comment]
Can we close?

**Comment by vaibhavsingh97** [comment]
@cclauss @bhaveshAn Closing
