### ISSUE TITLE
Should OrderedDicts be used to preserve rank order of search results?

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#315]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Search results are stored in a dict which changes the order of the results.

**Expected behavior:**

Search results are stored in an OrderedDict which preserves the order of the results

**Steps to reproduce:**
Print results before dict and after dict.

**Comment by ParthS007** [comment]
Is order a priority right now?

**Comment by schedutron** [comment]
Can we store results themselves in dictionaries and append the dictionaries to a list so that the original order is maintained?

**Comment by cclauss** [comment]
Closed as a non-issue.  @schedutron got it right.
