### ISSUE TITLE
Display results like a search engine

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#322]
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

![enhance1](https://user-images.githubusercontent.com/22936570/32567995-ee4aa410-c4b4-11e7-85f1-b3edff26ab28.png)

**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Comment by vaibhavsingh97** [comment]
@bhaveshAn what i can understand is right now we get this result is that we also get meta links

**Comment by bhaveshAn** [comment]
I mean to add the title and url returned by the api and make change to frontened to respond each result set having different div inside which we can have title and that title has href of the url of the result set

**Comment by AnshulMalik** [comment]
We are not displaying the results anywhere, we are just returning json or xml response

**Comment by bhaveshAn** [comment]
What ever may be the response `json` or `xml` . we can add a section where we display all the  responses (json / xml) as web response just like I uploaded a screenshot above.

It is a frontend thing not concerning backend.

**Comment by AnshulMalik** [comment]
I think we should stick to json response, it's a micro service, just provides data. The clients like susi or whatever are supposed to show the results in this manner.

**Comment by cclauss** [comment]
This might be a microservice but a minimal UI the help us debug the inputs and outputs is valuable.

There are a bunch of difference between [query-server running on heroku]() and query-server running locally.  Most absent are the results that appear below the query on heroku but not when run locally.  Also the JSON and XML buttons have no text when run locally and the Max dropdown is poorly placed.  Having a very similar look and feel between the two would help a lot in creating and debugging pull requests.

![query-server on heroku vs local](https://user-images.githubusercontent.com/3709715/33207486-31db6916-d10e-11e7-91d9-cb6d7fea3502.png)

**Comment by vaibhavsingh97** [comment]
@cclauss it's look like you haven't run `bower install` command. This will install necessary file that will fix the issue you are facing

**Comment by cclauss** [comment]
Perfect.  Thanks!

**Comment by gabru-md** [comment]
@bhaveshAn This issue is not clear. 
Query-Server is a service  that provides search results to the clients like SUSI. JSON and/or XML is the best possible way to provide such results.
And the primary aim of query-server is not to act as a search engine, but to provide data to clients engines like susi.
Am i right @AnshulMalik ?

**Comment by AnshulMalik** [comment]
Yep @gabru-md

**Comment by ParthS007** [comment]
Closing since query-server only provides data .
