### ISSUE TITLE
app not executing on Python 3

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#328]
Reopens #123 which was not fixed.

**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

app/server.py does not run on Python 3

**Expected behavior:**

app/server.py runs on Python 3

**Steps to reproduce:**

**Comment by shaddygarg** [comment]
I would like to work on this one. Is anyone presently working on it?

**Comment by cclauss** [comment]
https://github.com/fossasia/query-server/pull/297 is essential to this one.  After that look at the tests that are xfail in test in: https://github.com/fossasia/query-server/pull/297/files#diff-eff0198ff37b58d7351b62ca25b3f095 to get a sense of other issues we face.

**Comment by cclauss** [comment]
@shaddygarg Can you try to make the #297changes and then repeat this test https://github.com/fossasia/query-server/pull/297#pullrequestreview-73271423 ?

**Comment by shaddygarg** [comment]
Sure, I will open a WIP pull request!!
