### ISSUE TITLE
Add Facebook share button.

### ISSUE THREAD

**Issue by sinAshish** [fossasia/query-server#329]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

There is only option now for sharing via twitter now.
**Expected behavior:**

Facebook share button along with the twitter share button.
**Steps to reproduce:**

**Comment by sinAshish** [comment]
I would like to work on this issue.

**Comment by ParthS007** [comment]
claiming this because of inactivity

**Comment by sinAshish** [comment]
I wanted to work on it, but couldn't because of my exams.
