### ISSUE TITLE
Change of tweet message.

### ISSUE THREAD

**Issue by sinAshish** [fossasia/query-server#330]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Right now, the tweet only consists of a couple of hashtags, with no message of any  other kind.
**Expected behavior:**

The tweet should be like _Hey, Check out this new search engine with which you search on multiple platforms all at the same time._  Followed by a couple of hashtags, so that the people who see the tweet get to know about Query Server.
**Steps to reproduce:**

**Comment by soumya-ranjan7** [comment]
Hey. I would like to work on this.

**Comment by sinAshish** [comment]
I have already submitted a PR.

**Comment by raju249** [comment]
Claiming this due to inactivity!

**Comment by sinAshish** [comment]
I have already submitted a pr

**Comment by raju249** [comment]
It was not updated with new commits to `master` branch, and also since it was 18 days ago, I thought you might not be watching it, so just made a PR :smile: 
Anyways, let the maintainers decide.
