### ISSUE TITLE
Add Social Mention Support

### ISSUE THREAD

**Issue by S2606** [fossasia/query-server#338]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

http://socialmention.com/#

Would you like to work on this?
**Yes**

**Comment by S2606** [comment]
@bhaveshAn What do you think?

**Comment by vaibhavsingh97** [comment]
@S2606 Why we need this? can you please explain

**Comment by starlord1311** [comment]
should i take up this issue?

**Comment by starlord1311** [comment]
@S2606 @vaibhavsingh97  can i take up this issue?

**Comment by ParthS007** [comment]
Closing Since no more Search engines are required 👍
