### ISSUE TITLE
Parsijoo is not being tested by Travis CI

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#345]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Parsijoo is not being tested by Travis CI https://github.com/fossasia/query-server/blob/master/app/test_server.py#L40-L41

**Expected behavior:**

Parsijoo is being tested by Travis CI

**Steps to reproduce:**
Run the tests

**Comment by raju249** [comment]
Claiming this!
