### ISSUE TITLE
xml.dom.minidom.parseString to parse untrusted XML is vulnerable to attack

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#346]
https://www.codacy.com/app/fossasia/query-server/issues says: app/server.py
Using xml.dom.minidom.parseString to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.dom.minidom.parseString with its defusedxml equivalent function.

Line 71: xmlfeed = parseString(

**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Comment by cclauss** [comment]
Yes please

**Comment by starlord1311** [comment]
Can you tell what I am supposed to do? @cclauss

**Comment by rupav** [comment]
@starlord1311 you have to use a defusedxml function to do the role similar to that of  xml.dom.minidom.parseString because the latter is not a safe choice , susceptible to different threats (eg. billion laughs attack )

**Comment by cclauss** [comment]
Agreed...
1. add defusedxml to requirements.txt
2. use the parseString() in https://pypi.python.org/pypi/defusedxml#defusedxml-minidom instead of the standard library version.

**Comment by shaddygarg** [comment]
@starlord1311, you working on this?
