### ISSUE TITLE
Error running in docker

### ISSUE THREAD

**Issue by himanshukumar660** [fossasia/query-server#347]
**I'm submitting a ...**
- [ ] bug report

**Current behavior:**

The docker builds successfully, but when I use run command i get the following error :
```
Baracudda:~/Documents/Projects/query-server$ docker run query-server
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.9.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "app/server.py", line 2, in <module>
    from scrapers import feedgen
  File "/usr/src/app/app/scrapers/__init__.py", line 4, in <module>
    from google import Google
  File "/usr/src/app/app/scrapers/google.py", line 2, in <module>
    from generalized import Scraper
  File "/usr/src/app/app/scrapers/generalized.py", line 2, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
```

I have tried multiple times installing and uninstalling the urllib3 in order to match the requirements. But i don't know why i am not reaching to the final solution. 

Any help will be highly appreciated.

**Comment by vaibhavsingh97** [comment]
If you are using Ubuntu than first remove the package from the package manager:
`$ sudo apt-get remove python-pip`
And then install the latest version by side:
`$  easy_install pip`
`$ sudo pip uninstall requests`
`$ sudo pip install requests`
`$ sudo pip install --upgrade urllib3`
This will solve the issue

**Comment by himanshukumar660** [comment]
Still I am facing the same problem. Btw I am using mac OS X. But i tried to follow the above logic. Also when i run `pip show urllib3` i get the following output
`Baracudda:~$ pip show urllib3
Name: urllib3
Version: 1.22
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /Users/himanshukumar/anaconda/lib/python3.6/site-packages
Requires:`

**Comment by cclauss** [comment]
What happens when you do: __python2.7 -c "import requests"__

**Comment by himanshukumar660** [comment]
Yeah, it shows the following for python2.7
```
Baracudda:~/Documents/Projects/query-server$  python2.7 -c "import requests"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named requests
```
But works well with python3
```
Baracudda:~/Documents/Projects/query-server$  python3 -c "import requests"
Baracudda:~/Documents/Projects/query-server$
```

**Comment by cclauss** [comment]
pip install —upgrade pip

**Comment by himanshukumar660** [comment]
No Luck. I think the problem is due to the fact that in mac os, two
versions of python 2.7.

On Sun, Nov 26, 2017 at 5:14 PM, cclauss <notifications@github.com> wrote:

> pip install —upgrade pip
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/736448a916c8d07fdf346097d31305b3ed5f9150?url=https%3A%2F%2Fgithub.com%2Ffossasia%2Fquery-server%2Fissues%2F347%23issuecomment-347002763&userId=1839408&signature=d079b219912f3dbf>,
> or mute the thread
> <https://mailtrack.io/trace/link/568895d6c4d5735be5aef3bae9f086e8f4770593?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQFgzbGpPaiSJoO3mhZBzynVnwJQjoqOks5s6U83gaJpZM4QqMVo&userId=1839408&signature=fd0a316b7ba2489b>
> .
>



-- 
Himanshu Kumar
B. Tech (Penultimate year)
Computer Science and Engineering
Ph. no. - (+91) 9476001014
National Institute of Technology, Durgapur
Mahatma Gandhi Avenue,
Durgapur, West Bengal- 713209
India
