### ISSUE TITLE
Debug is True on deploying app to production to heroku

### ISSUE THREAD

**Issue by raju249** [fossasia/query-server#353]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

Best practice is debug should be False on deploying app to production to heroku.

**Steps to reproduce:**

I am taking this issue to work on.
Maintainers do let me know if `Debug=True` is intended while deploying or not.

**Comment by cclauss** [comment]
https://pypi.python.org/pypi/pytest-flask Seems to have a nice approach to fixing this so that debug is True in test but False in production.

**Comment by raju249** [comment]
Thanks @cclauss 
We can also try passing a command line arg while starting the app like for example `heroku` which will start with `debug=False` and if the arg is blank, it means to start a `dev` server.
What you think of this approach ?

**Comment by AnshulMalik** [comment]
Yep, can do that @raju249. We can also look for some environment variable like `production` or `debug` for the value.

**Comment by raju249** [comment]
claiming this :smiley:

**Comment by cclauss** [comment]
Default mode should be safe mode (debug is False).

**Comment by raju249** [comment]
Right @cclauss :+1:
