### ISSUE TITLE
GCI Task: Fix any open issue in query-server

### ISSUE THREAD

**Issue by ParthS007** [fossasia/query-server#355]
- **Objective**: Take any one open issue, study about the bug/feature which is in the issue and give a PR that solves that issue.

- **Requirements**: Git,HTML,CSS,Python,BeautifulSoup
- **Expected Outcome**: A pull request fixing that particular issue.
- **Type**: Code,Research
- **Time to Complete the task in days** : 5

**Comment by mariobehling** [comment]
This should go to the GCI site, not here.
