### ISSUE TITLE
Add QihooSo support

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#361]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

Add support for [Qihoo So](https://www.so.com/?src=www&fr=none) support

**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Comment by mariobehling** [comment]
Currently we need to focus on performance and have low priority for more search engines. Therefore closing it.
