### ISSUE TITLE
Fixing command for Local Development Setup

### ISSUE THREAD

**Issue by realslimshanky** [fossasia/query-server#366]
**I'm submitting a**
- [x] bug report

**Current behavior:**
Running `source activate venv` to activate virtual environment created on this [documentation](https://github.com/fossasia/query-server/blob/master/docs/installation/local.md) does not work.

**Expected behavior:**
Expected behavior with such a command should be activation of python virtual environment.

**Steps to reproduce:**
Simply follow all the steps given in this [documentation](https://github.com/fossasia/query-server/blob/master/docs/installation/local.md) upto `source activate venv`.

I would like to fix this issue by making a PR to the repository.

**Comment by raju249** [comment]
How about we use `virtualenv-wrapper` for activating and deactivating ?

**Comment by raju249** [comment]
With that we don't have to use `source activate`. Just `activate env_name` and `deactivate env_name`
Your thoughts ?

**Comment by realslimshanky** [comment]
@raju249 I recommend using [`pipenv`](https://docs.pipenv.org/) for virtual environment development which is also a recommendation of python.org now. I'll create an issue regarding this and start testing this project.

**Comment by raju249** [comment]
Cool stuff @realslimshanky 
Please go ahead 😄
