### ISSUE TITLE
Can we please shut down fossasia-bot?

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#376]
As discussed in https://github.com/fossasia/query-server/pull/349#issuecomment-347194797 @fossasia-bit generates a ton of superfluous messages that clutter the PR.  It assigns PRs to their author which as far as I can tell is both redundant and useless.  It then warns of conflicts which either echos information that GitHub has already provided or it is lying because there is no conflict.  It tells you if tests fail but GitHub, Travis, and Codasy already provide that data in a more consumable way.

**Comment by AnshulMalik** [comment]
Yep, I agree with you @cclauss

**Comment by niranjan94** [comment]
@cclauss the bot was meant as an experiment. I do agree it is a pretty chatty right now. But somethings like setting labels (needs review and ready to ship) is actually useful for big projects. 

And the reason the bot comments the information already provide by GH is that many contributors fail to see the status updates provided by travis. But when the bot comments by mentioning their username, they get a notification and actually see the issue. Leading to a faster response from the PR creator.

Another useful function of the bot is moving issues from one repo to the other. Which is pretty damn useful in multi-repo projects. 

But I do agree the bot is chatty. That could be fixed. Feel free to make a PR to https://github.com/niranjan94/github-automaton

**Comment by cclauss** [comment]
It is a bummer that GitHub web UI does not allow _contributors_ to set a few labels like __needs review__.  I think that humans can make that decision better than bots can.  I have written to GitHub on this topic several times but no positive response yet.  I do not see the value in adding the __ready to ship__ label given that the status of the PR always changes at the same time.

Moving issues from one repo to another sounds cool but does not apply here.

> Leading to a faster response from the PR creator.

I think we are reinforcing bad habits (ignoring test tools) and at the same time focusing on optimizing the wrong step in our process.  Our current issue is not that we are being too slow at creating PRs but that __we are too slow at reviewing and merging PRs__.  If I am reviewing PRs and I open #343 it is really difficult for me to evaluate if this PR is ready or not because there are 14 @fossasia-bot comments that clutter the PR log that are hiding the 5 comments made by humans.

fossasia-bot may have utility in other projects but here I believe that it is slowing us down in our key choke point: review --> merge.  I believe that we are better off without it.

**Comment by niranjan94** [comment]
It has been turned off for query-server.

**Comment by cclauss** [comment]
Thanks @niranjan94 

Do you have admin rights to help solve #332 ?

**Comment by niranjan94** [comment]
@cclauss nope. That isn't under my codacy account.
