### ISSUE TITLE
Where are our performance issues?

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#382]
Several PRs were recently closed with a message that we need to focus on performance.

Could we document here what we mean by performance and how we hope to increase it?

Do we mean?
- [ ] Server startup time
- [ ] Time from query to response on unique queries
- [ ] Time from query to response on repeated queries
- [ ] Speed when dealing with multiple callers simultaneously
- [ ] Other

**Comment by raju249** [comment]
#262 and #338 are still open. 
Can we please know why ?

**Comment by AnshulMalik** [comment]
May be @mariobehling forgot :P

**Comment by cclauss** [comment]
#341 would help us understand one aspect of performance.

**Comment by airsion** [comment]
can i do this issue
