### ISSUE TITLE
yandex is failing because of redirect to catpcha

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#387]
https://github.com/fossasia/query-server/issues/383#issuecomment-350889007

**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

We get no data

**Expected behavior:**

We get data

**Steps to reproduce:**
Run #385

**Comment by Dragneel7** [comment]
@cclauss The catpcha is there to prevent automated request. There is a service "https://xml.yandex.com"
that allows you to send automated request. Maybe that can help.

**Comment by starlord1311** [comment]
can i take this up?

**Comment by raju249** [comment]
Yandex for registration asks for a phone number. If we don't provide at the start, it only allows 10 xml calls per day.
Also there is account specific key. 
So here we have the following options to go with:
1. Stop the support of yandex
2. Provide a phone number and email to the one who will be working on this issue.

Your thoughts @cclauss 

cc @mariobehling

**Comment by cclauss** [comment]
My vote would be for dropping the Yandex scraper but the project maintenaners might have a different point of view.

**Comment by raju249** [comment]
+ @vaibhavsingh97 
+ @djmgit 
+ @bhaveshAn

**Comment by vaibhavsingh97** [comment]
@cclauss I think we have to figure a way out instead of droping the support
