### ISSUE TITLE
Correction in readme

### ISSUE THREAD

**Issue by yashLadha** [fossasia/query-server#400]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Comment by AnshulMalik** [comment]
Can you please elaborate this issue ? I think this is platform specific.

**Comment by yashLadha** [comment]
To start the mongo database, there is a need to start `mongodb` contrary to `mongod` service.

**Comment by raju249** [comment]
@yashLadha I think we can open this small issues but keep them open for the beginner contributors who may need a moral push once their PRs are merged, so that they can move around the codebase and get encouraged to do more.

What you think ?
cc @AnshulMalik

**Comment by yashLadha** [comment]
Yaa I also think to add this issue in gci as well.

**Comment by raju249** [comment]
yeah, we can do that

**Comment by AnshulMalik** [comment]
@raju249 Good point.

**Comment by AnshulMalik** [comment]
Let's chat on gitter?

**Comment by raju249** [comment]
The general link doesn't seem to work.

**Comment by ParthS007** [comment]
Closing this because of lack of clarity what changes are to be done. Please open new issue with proper description 👍
