### ISSUE TITLE
Update in Readme

### ISSUE THREAD

**Issue by umangahuja1** [fossasia/query-server#402]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Usage link present in readme is not required as it is unreferenced.

**Expected behavior:**

Updated readme after removing that line. No change in behavior.

**Steps to reproduce:**
Simply remove the line from readme.

**Comment by Shivamgera** [comment]
I would like to work on this issue.

**Comment by umangahuja1** [comment]
I have already sent a PR.
