### ISSUE TITLE
small_test() is broken: search() is missing a parameter

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#404]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

small_test() at https://github.com/fossasia/query-server/blob/master/app/scrapers/__init__.py#L34-L35 will raise an exception.

**Expected behavior:**

small_test() works as expected

**Steps to reproduce:**
Call small_test()

**Comment by dgarvit** [comment]
Thanks for finding this little bug! This probably has to do with invalid function call.
