### ISSUE TITLE
Quer-server doesn't seem to work on a smaller window

### ISSUE THREAD

**Issue by dgarvit** [fossasia/query-server#406]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Query server doesnt seem to work when the window size is resized to a smaller one.

**Expected behavior:**

Query server works when the window size is resized to a smaller one.

**Steps to reproduce:**
Resize the window size to a smaller one.

Representation: 
![fossasia](https://user-images.githubusercontent.com/24482726/34356805-2c053e1e-ea67-11e7-9dad-57c1264c9ef9.gif)

**Comment by dgarvit** [comment]
Yes, I'd like to work upon it.

**Comment by vaibhavsingh97** [comment]
@dgarvit Please send PR for the same
