### ISSUE TITLE
Disable Yandex for now

### ISSUE THREAD

**Issue by dgarvit** [fossasia/query-server#407]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

In reference to #387.

I'd like to work upon this once maintainers confirm it.

**Comment by bhaveshAn** [comment]
Disabling any existed support would not be nice way to go.
I still think, there may be some solution to it.
So, we should collaboratively find some solution to it.
@fossasia/query-server-searss-devs Can we, please have a discussion on it.

**Comment by vaibhavsingh97** [comment]
Sure! Can move to gitter for further discussion

**Comment by dgarvit** [comment]
@bhaveshAn definitely. But until we get to a solution, i think disabling it should be a better idea. Definitely we need to fix it, but it causes the server to keep making constant requests, and return empty results. In most cases the process needs to be killed and server be restarted. It is not right to keep something enabled which is not working for now. Work out a solution and then we will enable it again. :smile:

**Comment by dgarvit** [comment]
@bhaveshAn @vaibhavsingh97 your views?

**Comment by bhaveshAn** [comment]
Sure, In my views, you can modify the yandex button (under buttons' disable property of bootstrap) but not removing the button.
