### ISSUE TITLE
Empty search result for Yahoo

### ISSUE THREAD

**Issue by niranjan94** [fossasia/query-server#41]
Yahoo search is not working. 

More info here: https://github.com/fossasia/query-server/pull/40#issuecomment-287246522

**Comment by abhishek1995s** [comment]
![image](https://cloud.githubusercontent.com/assets/14086935/24087692/4aa468e2-0d48-11e7-9533-3bfae43330e0.png)
@niranjan94 Got it correctly will updated soon after some testing

**Comment by abhishek1995s** [comment]
@niranjan94 Since the bug has been resolved it will be better to close this issue
