### ISSUE TITLE
Replacing Buttons with Dropdown

### ISSUE THREAD

**Issue by gabru-md** [fossasia/query-server#410]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Currently we have buttons for all separate scrappers
**Expected behavior:**

It is a bit untidy and so I suggest adding a dropdown with all the scrappers to choose from.

**Would you like to work on it**
Yes, I would like to work on this issue.

**Comment by ParthS007** [comment]
I was just opening this

**Comment by gabru-md** [comment]
Available for GCI Students as of now!

**Comment by abishekvashok** [comment]
@ParthS007 @gabru-md can I do it?

**Comment by gabru-md** [comment]
Sure buddy
