### ISSUE TITLE
Refactor Code and Improve Documentation  

### ISSUE THREAD

**Issue by umangahuja1** [fossasia/query-server#415]
**Changes to be done:**

- [ ] Though csv feature is working but csv format not present in readme.
- [ ] Remove repeated auto-deployment buttons of Heroku and Docker.
- [ ] Python 2.7 and 3.6 are both tested and supported (See __.travis.yml__)
- [ ] In __server.py__, search() is too complex and should be broken into multiple functions.

**Please ask on Gitter channel if you have any doubt in above-listed points.**

**Comment by cclauss** [comment]
This PR has a useless title.

**Comment by ParthS007** [comment]
@umangahuja1  Nice catch, GCI students can do it

**Comment by umangahuja1** [comment]
It was a minor change so I didn't bother. Still suggest something useful please.

**Comment by umangahuja1** [comment]
@ParthS007 I will find some more, but for this I have already sent a PR. Didn't saw that comment. Still you can reject if you want to keep for GCI

**Comment by ParthS007** [comment]
@umangahuja1  Add all the other minor changes to be done here and GCI students will do it 👍

**Comment by umangahuja1** [comment]
Sure.
Will add more if I come across any. I think we should create separate issues or combine 2-3 changes if encountered simultaneously in an issue together.

**Comment by ParthS007** [comment]
add all the bugs with a checklist here and students will give multiple PRs for it 👍

**Comment by umangahuja1** [comment]
Okay nice idea. :+1:

**Comment by cclauss** [comment]
- [ ] Python 2.7 and 3.6 are both tested and supported (See __.travis.yml__)
- [ ] In server.py, search() is too complex and should be broken into multiple functions.

**Comment by ParthS007** [comment]
thanks, @cclauss  added it to the checklist.

**Comment by ParthS007** [comment]
@fossasia/query-server-searss-devs  Please add all issues here which can be solved by GCI participants. 👍

**Comment by bhaveshAn** [comment]
Sure @ParthS007

**Comment by 0x48piraj** [comment]
@ParthS007 No tasks are there for query server.
Although, I'll do it :+1:

**Comment by bhaveshAn** [comment]
Can be closed.
