### ISSUE TITLE
One source of scraper names, not three.

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#423]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

Adding new scrapers to the system is too complex because the name of the scraper must be correctly entered in three places (plus README.md):
1. https://github.com/fossasia/query-server/blob/master/app/scrapers/__init__.py#L17-L31
2. https://github.com/fossasia/query-server/blob/master/app/server.py#L26-L28
3. https://github.com/fossasia/query-server/blob/master/app/test_server.py#L33-L34

**Expected behavior:**

When adding a new scraper to the system, its name is entered in 1. and then both __server.py__ and __test_server.py__ do __from .scrapers import scrapers__ to get the names of the scrapers instead of creating their own hardcoded lists in 2. and 3.

**Steps to reproduce:**

**Comment by dilraj45** [comment]
Creating a constant file containing all the hard-coded string and referring to these constants wherever necessary could be alternate approach for achieving the expected behavior. If this issues hasn't been assigned to anyone then, i would like to take this up. And please, do let me know which approach will be more suitable

**Comment by cclauss** [comment]
I hope that in the end we autoload the scraper names by looking in the classes defined in __app/scrapers__ but it has taken me some time to get #342 approved.  I will get to it eventually but this is a good stepping stone.

See: https://github.com/fossasia/query-server/pull/342/files#diff-0aae1cd6587ddccb7df807d245dcbd4aR67

**Comment by dilraj45** [comment]
Yeah, that will be great. I'll try to look into issue [#424](https://github.com/fossasia/query-server/pull/424), and will see if i can be of any help to you.
