### ISSUE TITLE
naming convention 

### ISSUE THREAD

**Issue by lawrencenull** [fossasia/query-server#430]
**I'm submitting a ...**
- [ ] bug report
- [*] feature request

It appears that soon there will be video and image results. Is there a naming convention established yet? Once the deploy bug is handled i would like to try my hand at this, I'm new to python but it seems pretty straightforward to create a scraper. I would propose as follows for naming if a standard convention isn't already in place:

<'search engine name' - 'specific item'>

/api/v1/search/google-images?query=query&format=format
/api/v1/search/google-video?query=query&format=format

/api/v1/search/bing-images?query=query&format=format
/api/v1/search/bing-video?query=query&format=format

etc...

**Comment by cclauss** [comment]
Our [API documentation](https://github.com/fossasia/query-server/blob/master/README.md#api) shows that we already use __format__ to mean the output format (json, xml, csv).  You will need to select a different word or we would need to make a breaking change to our API.

**Comment by lawrencenull** [comment]
Sorry i wasn't clear I was meaning the search engine name for the asset.

/api/v1/search/<bing-images>?query=query&format=format
/api/v1/search/<bing-videos>?query=query&format=format

etc

**Comment by bhaveshAn** [comment]
Not required.
Already the API is nice.
Thanks for suggestions.
