### ISSUE TITLE
Re-Design UI

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/query-server#445]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
![image](https://user-images.githubusercontent.com/5800726/35085072-f8e11876-fc4c-11e7-80ae-89b80342744b.png)

**_The current design is pretty haywire and not looks good to see and to use._**

**Expected behavior:**
- Design should look ordered.
- Should be easy to use.

## Raw UI Screenshots : 
![image](https://user-images.githubusercontent.com/5800726/35085132-3bc4d498-fc4d-11e7-9bfc-d21c2842d534.png)

# OR

![image](https://user-images.githubusercontent.com/5800726/35085321-2dc0791e-fc4e-11e7-89fa-7e679b0bc4fd.png)

**Comment by 0x48piraj** [comment]
ping @fossasia/query-server-searss-admin @fossasia/query-server-searss-devs 👍

**Comment by duttaditya18** [comment]
@0x48piraj Awesome idea! The current layout works pretty well though.

**Comment by 0x48piraj** [comment]
Should I proceed ?

**Comment by duttaditya18** [comment]
@0x48piraj I think you totally should! But please wait for the conformation of someone who knows more than me! 😄

**Comment by 0x48piraj** [comment]
Yes, I'm waiting for core-developers only 😉

**Comment by Remorax** [comment]
@0x48piraj I think the latter looks better. Just make sure its' aligned properly and the submit button is on the bottom. I think that would look better 😄

**Comment by 0x48piraj** [comment]
On it!

**Comment by raju249** [comment]
Also @0x48piraj please take care of different screen sizes.
Good luck

**Comment by realslimshanky** [comment]
@0x48piraj Hi, any progress on this issue?

**Comment by bhaveshAn** [comment]
Right now we are having nice UI. Also none of screenshots provided in Expected behavior looks good to me. May be we can try something new, but not repositioning the different items.

**Comment by realslimshanky** [comment]
@bhaveshAn agreed. An entirely new UI would be a better option to go with in order to better enhance visitor's experience. Elements on the website have been added up until now as per need. We can redesign how they look in order to enhance the styling.

**Comment by 0x48piraj** [comment]
Any ideas? @realslimshanky @bhaveshAn
These details are very vague.

**Comment by Pk13055** [comment]
@mariobehling Is this a priority as of now? I can pick this up if required.
