### ISSUE TITLE
Combine server and scrapper onto a single platform

### ISSUE THREAD

**Issue by niranjan94** [fossasia/query-server#45]
Right now we have the following:
- Server in Node.js
- Scrapper in python

and the server executes the python as a process. Which is not efficient at all. Imagine once this is integrated into the Open Event project. There might be many API calls coming to the query-server and each of these API calls will be spawning a new python process. We'll be having so many process spawns (one for each API call).

This will also make adding unit tests etc easier since all is in a single platform.

Instead, we are looking to implement the following
- [ ] Server also in python (A micro-framework or a basic server would do. Flask or werkzeug is recommended). The scrapper will be a python module in the server. (No more process spawns for API calls. Response would be quicker too)
- [ ] Dockerfile needs to be adjust accordingly

**Comment by abhishek1995s** [comment]
![screenshot from 2017-04-06 16-16-21](https://cloud.githubusercontent.com/assets/14086935/24751129/06bc7fe2-1ae6-11e7-88a8-180ae4f20ca4.png)
![screenshot from 2017-04-06 16-16-55](https://cloud.githubusercontent.com/assets/14086935/24751138/0f4ce26e-1ae6-11e7-9426-193c628f8634.png)
@niranjan94 implemented both web interface and API using flask framework

**Comment by niranjan94** [comment]
Please keep all frontend and the API structure just like the current node.js implementation. 

From the looks of it, the following seem different
- The frontend UI seems to be lacking the syntax highlighting that we have now
- The API URL is different.
- The json API schema should be of the format 
```js
[
    {
        'title': 'string',
        'link': 'string'
    }
]
```

Also, make a PR so that the code could also be reviewed.

**Comment by abhishek1995s** [comment]
@niranjan94  what is the required url format for the api I will change accordingly

**Comment by niranjan94** [comment]
@abhishek1995s please check the existing codebase

**Comment by abhishek1995s** [comment]
okay

**Comment by niranjan94** [comment]
@abhishek1995s we need the API endpoint like this.

`GET /api/v1/search`

Can accept the following query parameters.
1. `query` - will contain the query to search for *(required)* parameter.
2. `format` - can have either `json` or `xml` (default: `json`)

**Examples:**
1. `GET /api/v1/search?query=hello&format=xml`
1. `GET /api/v1/search?query=hello+world&format=xml`
1. `GET /api/v1/search?query=hello+world`
1. `GET /api/v1/search?query=hello+world&format=json`

**Comment by niranjan94** [comment]
@enigmaeth 

**Error responses:**
- Incorrect search engine - return `404 - Not Found`
- Zero responses - return `404 - Not Found`
- if `format` is something other than xml or json - return `400 - Bad Request`
- if `query` is empty or missing - return `400 - Bad Request`
