### ISSUE TITLE
typo in local installation guide

### ISSUE THREAD

**Issue by nityanandagohain** [fossasia/query-server#453]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

In the local installation guide
![screenshot from 2018-01-21 14-15-05](https://user-images.githubusercontent.com/26831659/35192338-00ae04e0-feb6-11e7-9a0a-d7bb375c6007.png)

**Expected behavior:**

It should be `sudo service mongodb start`

I would like to work on this issue.

**Comment by datboiee** [comment]
On it!

**Comment by nityanandagohain** [comment]
@datboiee Actually I have already submitted an PR
