### ISSUE TITLE
APP CRASH!

### ISSUE THREAD

**Issue by datboiee** [fossasia/query-server#460]
**I'm submitting a ...**
- [[*]](https://imgur.com/a/zS4ii) bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Comment by datboiee** [comment]
https://imgur.com/a/zS4ii

**Comment by bhaveshAn** [comment]
Check out https://query-server.herokuapp.com/

**Comment by datboiee** [comment]
It is still not working

**Comment by datboiee** [comment]
https://imgur.com/a/3bRUA
