### ISSUE TITLE
Do we need the search_without_count() functions?

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#461]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

We have many repetitive functions that I believe could be eliminated.

**Expected behavior:**

Fewer functions required to deliver the equivalent functionality.

**Steps to reproduce:**
Our scrapers have:
* [__def search(self, query, num_results, qtype=''):__](https://github.com/fossasia/query-server/blob/master/app/scrapers/generalized.py#L52) and
* [__def search_without_count(self, query):__](https://github.com/fossasia/query-server/blob/master/app/scrapers/generalized.py#L76)
but perhaps we could remove the second and only have the first.

When we do a __search()__ we are not guaranteeing that we will deliver at least __num_results__ results.  If the upstream search engine only delivers 5 results then we will only return that many even if the caller has set __num_results__ to 10.  If the upstream search engine does not allow us to control how many results we can get then we are not breaking any guarantee if we deliver less than __num_results__.  We are however guaranteeing that we will deliver no more than __num_results__.

So, why not have a default value for the num_results parameter (__def search(self, query, num_results=10, qtype=''):__) and do away with the _without_count_ functions?  Different scrapers could set their default value higher or lower.  The final return could ensure that no more than the requested number of urls are returned with `return urls[:num_results]`

Thoughts?

**Comment by ankan17** [comment]
Can I work on this issue?

**Comment by cclauss** [comment]
@ankan17 I see no problem with that but it will require good tests as well.

**Comment by bhaveshAn** [comment]
Its not a valid issue see the reasons 
Go to https://www.youtube.com/results?search_query=fossasia and tell me if there's any page index.
```
Since few search engines are there which shows all the results on there first page, hence we doesn't require any page index and codebase added for such search engines support too. Example: Quora, youtube.
```

**Comment by cclauss** [comment]
It is a valid issue the way that it is written above:
* So, why not have a default value for the num_results parameter (__def search(self, query, num_results=10, qtype=''):__)

That deals adequately with your objection.  query-server in not going to return an infinite number of results just because the upstream search engine does so.

**Comment by ankan17** [comment]
@cclauss You mean I have to write the tests as well?

**Comment by cclauss** [comment]
Yes, please.  We now have plenty of examples:
* https://github.com/fossasia/query-server/tree/master/test

**Comment by ankan17** [comment]
I have eliminated the use of search_without_count() entirely and these are the changes caused:

+ No change to the search engines except youtube and quora. Working as they worked previously.
+ Quora now provides all the results as it would without any count (don't know why but quora returns a maximum of 10 results even when the count is set higher). Only change is that quora search now responds to a count less than the number of results provided which was not the case earlier.
+ Youtube without any count returns a maximum of 10 results and with count returns "count" number of results or lesser if the number of results are lesser. Earlier youtube did not respond to count which has been changed now.

Is this the desired behavior? @cclauss

**Comment by cclauss** [comment]
Nice progress @ankan17 

I believe that your findings correspond with my notes above.  For Quora and YouTube, you can set __num_results=10__ given that is what the upstream search engine seems to default at.  If the caller sets __num_results=100__ then the query server will only return 10 as I discussed above.  Thanks for your work on this important simplification.

**Comment by ankan17** [comment]
Youtube gives more than 10 results. The current behaviour is: Quora returns a max of 10 results even if **num_results=100** because that is what the quora engine returns. Youtube gives more than 10 results. So if **num_results=100**, youtube returns all the results (less than 100). Without count, both quora and youtube return a maximum of 10 results. So, I guess I don't need to change any more code?

Also please can you explain what do I need to do with the tests? @cclauss What new tests should I write or which existing tests should I modify?

**Comment by cclauss** [comment]
Three tests on a popular search term like “Fossasia” for each scraper:
1) do not supply a __num_results__ value and test that default value number of results are returned
2) supply __num_results=2__ and then test that exactly 2 results are returned
3) supply __num_results=27__ and then test that exactly 27 results are returned (or explain in the test why fewer that 27 will be returned).

Happy hunting!

**Comment by ankan17** [comment]
Do I modify the existing tests which employ search_without_count() or delete them? @cclauss

**Comment by bhaveshAn** [comment]
Make your own no need to delete

**Comment by ankan17** [comment]
@bhaveshAn But the tests that have search_without_count() will fail since there is no such function

**Comment by cclauss** [comment]
Yes.  Those ones you need to modify or delete.
