### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#466]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

No `package-lock.json` present.
**Expected behavior:**

`package-lock.json` file has to be commited to version control and **not** to add in `.gitignore`
https://medium.com/@Quigley_Ja/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8#1c9a

**Steps to reproduce:**

**Yes, Wanna work on this issue**

**Comment by cclauss** [comment]
Do folks install query-server with npm?

https://docs.pipenv.org claims to automagically add npm support to Python projects.  Does pipenv's __Pipfile.lock__ file serve a similar to __package-lock.json__ or completely different?  I know little about npm.

**Comment by realslimshanky** [comment]
@cclauss we only use `npm` for `bower` or other node packages and `pipenv` for all python packages. Hence, you can say adding `package-lock.json` gives us similar functionality to what `Pipfile.lock` gives us for python.
