### ISSUE TITLE
mongodb instead of mongod in the local installation docs

### ISSUE THREAD

**Issue by ankan17** [fossasia/query-server#471]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The ![local.md](https://github.com/ankan17/query-server/blob/master/docs/installation/local.md) file in the docs/installation folder currently says `sudo service mongod start` which gives an error when run on Ubuntu.

**Expected behavior:**
It should instead say `sudo service mongodb start`

**Steps to reproduce:**
Just try to start or stop the service "mongod".

**Comment by ankan17** [comment]
This is just a possible error in the docs which I encountered during installation. Can I get assigned to this issue?

**Comment by rupav** [comment]
https://github.com/fossasia/query-server/pull/454. Already a PR regarding this issue, also see commenTs. Mongod is correct indeed.

**Comment by ankan17** [comment]
Okay. Thanks for the clarification. Closing this issue.
