### ISSUE TITLE
Google image search is not working

### ISSUE THREAD

**Issue by dgarvit** [fossasia/query-server#482]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Google image search does not work

**Expected behavior:**

Google image search should work

**Steps to reproduce:**
Try searching a query on Google and type image.

Yes, I'd like to work on this issue.

**Comment by vaibhavsingh97** [comment]
Hi @dgarvit I was working on it and can you give me some time to send PR

**Comment by dgarvit** [comment]
Sure @vaibhavsingh97 . my apologies I assumed the feature has been integrated :smile:
