### ISSUE TITLE
Small UI bug in mobile view

### ISSUE THREAD

**Issue by realslimshanky** [fossasia/query-server#483]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
A small bug in UI can be seen when choosing 'duckduckgo' or 'dailymotion' while in mobile view as below. Also, the padding of the dropdown and it's label i.e. `Engine:` is not correct as it is touching the boundary.

![image](https://user-images.githubusercontent.com/10004530/35485355-7252c5e4-0484-11e8-87f9-0eac15b004b4.png)

![image](https://user-images.githubusercontent.com/10004530/35485350-65eefab6-0484-11e8-8875-fe0d7750be4a.png)

**Expected behavior:**
UI should be elegant and responsive.

**Steps to reproduce:**
Simply visit the [original](http://query-server.herokuapp.com/] website on the smartphone or on the desktop using developer's tool to get a simulated mobile view to reproduce the bug.

**Comment by rupav** [comment]
@realslimshanky I would like to work on it.

**Comment by realslimshanky** [comment]
@rupav nice. would be waiting for your PR.
