### ISSUE TITLE
Refactoring code

### ISSUE THREAD

**Issue by Remorax** [fossasia/query-server#484]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The current code very badly needs to be refactored, since after addition of image, video and news search a lot of dead code has sprung up.

**Expected behavior:**
The code needs to be refactored.

I would like to work on this.

**Comment by realslimshanky** [comment]
@Remorax could you please share an example of where the issues lie and how you are planning to refactor it?

**Comment by Remorax** [comment]
@realslimshanky  Most of the functions in `generalized.py`, like `video_search_without_count`,`image_search_without_count`, `video_search` take up around 50-60 lines of code and are entirely redundant. The reason I had made the function `call_appropriate_parser` while making the PR for Yahoo Search is to avoid this redundancy. But the people who made the PRs for the other search engines didn't use that function and ended up making one function for every `queryType`.
Also the if-else conditions in `get_page` take up around 20 lines and some of the condition blocks are again redundant and can be shortened quite a bit.
Hope that gives you the basic idea 😄
