### ISSUE TITLE
Remove inline css

### ISSUE THREAD

**Issue by rupav** [fossasia/query-server#492]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Inline css.
**Expected behavior:**

seperate css file.

**I am working on it**.

**Comment by rupav** [comment]
@vaibhavsingh97 @cclauss . Suggest if any other css file needs to be created, I will be editing already created style.css otherwise.

**Comment by realslimshanky** [comment]
It's better to have just one css file to contain all the styling needs. You can also make is possible by modifying the existing ones.

**Comment by rupav** [comment]
@realslimshanky you can review https://github.com/fossasia/query-server/pull/493, made changes in already existing styles.css file only.
