### ISSUE TITLE
Return appropriate error responses.

### ISSUE THREAD

**Issue by niranjan94** [fossasia/query-server#50]
- Incorrect search engine - return `404 - Not Found`
- Zero responses - return `404 - Not Found`
- if `format` is something other than `xml` or `json` - return `400 - Bad Request`
- if `query` is empty or missing - return `400 - Bad Request`

Along with the proper HTTP Status code header, the body should also contain the error message in either json or xml (depending on what was asked by the user)

**Comment by enigmaeth** [comment]
> if format is something other than `xml` or `json` - return 400 - Bad Request

This, and that default format is json implies currently that requests of the form `google/query=wiki&format=` will return JSON response. An error is returned only when the format is in none of these forms :  `format=json` or `format=xml` or `format=` .
