### ISSUE TITLE
engines in dropdown should be in alphabetic order.

### ISSUE THREAD

**Issue by rupav** [fossasia/query-server#501]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

![2018-02-12 2](https://user-images.githubusercontent.com/20624380/36083929-255d4cf4-0fde-11e8-9509-09ca3f766810.png)
Its random.
**Expected behavior:**

with Alphabetic order, should be the list of engines
**Steps to reproduce:**
Go to http://query-server.herokuapp.com/, open engine dropdown.

**Comment by rupav** [comment]
I am working on it.

**Comment by vaibhavsingh97** [comment]
Hi Rupa,

This is a beginner friendly issue. Please work on advance issue to make
this app stable
