### ISSUE TITLE
How do I scrapper for new Search Engine?

### ISSUE THREAD

**Issue by daxeel** [fossasia/query-server#504]
I want to add a new search engine scrapper. I could not find any doc for this purpose. Can anyone please guide me to the process?

**Comment by vaibhavsingh97** [comment]
Hi @daxeel 👋 
welcome to FOSSASIA!
Please open issue for the same, describing the name of search engine and purpose of adding.

**Comment by realslimshanky** [comment]
@daxeel also read through the code of how other search engines are made. It's pretty straight forward.

**Comment by daxeel** [comment]
@vaibhavsingh97 Ok. I will open an issue.
@realslimshanky I went through the code already.

**Comment by rupav** [comment]
@daxeel you can see earlier pull requests which add search engines. There are many closed and merged for reference. You will get the idea how scraping works , and the workflow too.
