### ISSUE TITLE
Take out "project box" on start page and move version info to bottom

### ISSUE THREAD

**Issue by mariobehling** [fossasia/query-server#512]
The start page has project info that is already covered in the code repo. Please take out the box and only keep "version information". Move version info to the middle on the bottom of the page.

![screenshot from 2018-09-03 07-18-55](https://user-images.githubusercontent.com/1583873/44968733-dd980100-af49-11e8-960b-a84fd3b50b15.png)

**Comment by nalawadepiyush** [comment]
@mariobehling  what enhancement do you need here can you elaborate? I'll try to solve this issue today itself.

**Comment by bhaveshAn** [comment]
@nalawadepiyush This is what the objective is 

> Please take out the box and only keep "version information". Move version info to the middle on the bottom of the page.
