### ISSUE TITLE
Take out "Submit" button and use JSON, XML or CSV as submit

### ISSUE THREAD

**Issue by mariobehling** [fossasia/query-server#513]
Instead of using "Submit" the user should get the results when they hit JSON, XML or CSV. 

![screenshot from 2018-09-03 07-21-56](https://user-images.githubusercontent.com/1583873/44968799-2ea7f500-af4a-11e8-9bc9-de8bafd8e3dc.png)

**Comment by Anupam-dagar** [comment]
@mariobehling I would like to work on it.
