### ISSUE TITLE
Attach Search box components

### ISSUE THREAD

**Issue by mariobehling** [fossasia/query-server#516]
The search box components are currently separated. Please implement them in the same way as https://api.loklak.org.

![screenshot from 2018-09-03 07-37-28](https://user-images.githubusercontent.com/1583873/44969180-3bc5e380-af4c-11e8-89c3-85ee2373bf5c.png)

![screenshot from 2018-09-03 07-35-52](https://user-images.githubusercontent.com/1583873/44969163-218c0580-af4c-11e8-8e26-95cc329721a7.png)

**Comment by dewanshrawat15** [comment]
Is the issue still open to work open..?? The attaching of the search box components..??

**Comment by dewanshrawat15** [comment]
@mariobehling Is the issue assigned to someone or can I start working on it directly ?

**Comment by dewanshrawat15** [comment]
I want to work on this issue, please assign me.
