### ISSUE TITLE
Hashtag Search Not Working in Web Interface and Loklak API Request

### ISSUE THREAD

**Issue by vkartik97** [fossasia/query-server#517]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
- The Query sent to Loklak Server for Twitter Query is not URL Encoded, causing issue in Response from it.
- When using Hashtags for Search on Web Interface, it gives 404 Error, as the GET Request is missing the Query  : `http://localhost:7001/api/v1/search/google?query=`

**Expected behavior:**
The query-server should return the result for Hashtag Search.

**Comment by bhaveshAn** [comment]
Resolved by https://github.com/fossasia/query-server/pull/511 hence closing
