### ISSUE TITLE
Syntax-highlighting missing for JSON response

### ISSUE THREAD

**Issue by niranjan94** [fossasia/query-server#52]
<img width="1680" alt="screen shot 2017-04-19 at 10 09 38 am" src="https://cloud.githubusercontent.com/assets/2404372/25163477/54b1f5ea-24e8-11e7-9a2c-f449f442d020.png">

**Comment by Pk13055** [comment]
I would like to pick this up. What exactly do you mean by syntax highlighting?

**Comment by jajodiaraghav** [comment]
Hi @Pk13055 
Are you working on this or can I take this?

**Comment by Pk13055** [comment]
I am working on it.

**Comment by vaibhavsingh97** [comment]
@Pk13055 Update your status please

**Comment by starlord1311** [comment]
can i take up this issue?

**Comment by starlord1311** [comment]
i am new to open source

**Comment by vaibhavsingh97** [comment]
@starlord1311 yes you can take this issue as @Pk13055 haven't updated his status.

**Comment by starlord1311** [comment]
can you tell what i am supposed to do as i am not getting it @vaibhavsingh97

**Comment by raju249** [comment]
@starlord1311 Can you please share any update on this ?

cc @vaibhavsingh97

**Comment by ParthS007** [comment]
closing with reference to #300
