### ISSUE TITLE
Permission to work on issue #512, #515, #516

### ISSUE THREAD

**Issue by dnuka** [fossasia/query-server#522]
Hi `fossasia/query-server` community!

My name is Dhanuka. I am from Sri Lanka. I am a self taught software developer and I would love to work on  #512 , #515 , #516  issues all together and submit one PR as my first contribution to the project as a participant of Codeheat. Is it OK to work on them all together or should I work on one at a time in three PRs? Any help is appreciated. @mariobehling  @bhaveshAn 

update
-----------
I'm pretty excited to get started. Should I have to wait, until you guys assign this to me or is it OK if I get started? Waiting to hearing from you. @mariobehling @bhaveshAn @cclauss @enigmaeth @niranjan94 @niccokunzmann 

Thank you.

**Comment by vkartik97** [comment]
@dnuka 
Please post messages on https://gitter.im/fossasia/query-server and not here.

**Comment by bhaveshAn** [comment]
@dnuka If you find nobody working on any of these issues, then you can take it one at a time. Cheers!

**Comment by dnuka** [comment]
@bhaveshAn Thank you. Can you review #527
