### ISSUE TITLE
Add Insturctions for Fork Syncing

### ISSUE THREAD

**Issue by vkartik97** [fossasia/query-server#525]
**I'm submitting a ...**
- [x] feature request

Contributors new to Open Source might have issue keeping their fork updated with the Project.
Instructions from the following Help Pages from GitHub can be added to [README.md](https://github.com/fossasia/query-server/blob/master/README.md) :
- https://help.github.com/articles/configuring-a-remote-for-a-fork/
- https://help.github.com/articles/syncing-a-fork/

**Comment by rohitjain00** [comment]
I'll be working on it
