### ISSUE TITLE
Using enter to display a query

### ISSUE THREAD

**Issue by rohitjain00** [fossasia/query-server#529]
**I'm submitting a ...**
- feature request

**Current behavior:**
When we type any text in the search box and press enter nothing happens.

**Expected behavior:**
After we type any text in the search box and press enter a search result with by default JSON format should be displayed.

**Steps to reproduce:**
Add a jquery keypress event to submit the form when enter key is pressed.

**Comment by phoenixking25** [comment]
@rohitjain00 assign me this

**Comment by rohitjain00** [comment]
@phoenixking25 A PR for this issue is already placed.
