### ISSUE TITLE
Auto-deploy query server on merged pull request on Heroku

### ISSUE THREAD

**Issue by mariobehling** [fossasia/query-server#54]
Please set up the query server on Heroku from the master branch and add the info to the Readme.md.

**Comment by niranjan94** [comment]
@mariobehling we already have that -> https://query-server.herokuapp.com/

**Comment by mariobehling** [comment]
Oh, missed it. It should be added to the Readme then, please.
Thanks.

**Comment by enigmaeth** [comment]
@mariobehling  It is there is the repo description. Should I add to the Readme file also?
