### ISSUE TITLE
Typo in local development setup instructions

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/query-server#552]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

![query-server-local-md at master anupam-dagar-query-server 02-10-2018 21-31-31](https://user-images.githubusercontent.com/21174572/46361163-96a54480-c68a-11e8-8c29-600f501440d2.png)
currently it is sudo service `mongod` start

**Expected behavior:**

It should be sudo service `mongodb` start

**Steps to reproduce:**
https://github.com/fossasia/query-server/blob/master/docs/installation/local.md

**Comment by prabhupant** [comment]
@Anupam-dagar it's correct. Refer to the docs here https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by Anupam-dagar** [comment]
It was giving some error with mongod,I did with mongodb and it executed successfully,that's why I thought it was a typo.
