### ISSUE TITLE
Increase number of results to 100

### ISSUE THREAD

**Issue by mariobehling** [fossasia/query-server#59]
Currently search results are limited to 10 results. Please increase the output to 100 results per search.

**Comment by rupav** [comment]
@mariobehling  Please close this issue. I can see required changes on [https://query-server.herokuapp.com/](url)

**Comment by gabru-md** [comment]
Should be closed according to #128

**Comment by cclauss** [comment]
Should this issue be closed?

**Comment by AnshulMalik** [comment]
This can be closed @mariobehling

**Comment by bhaveshAn** [comment]
@mariobehling Please close this in relation to #128
