### ISSUE TITLE
Develop different scrapers that can plug into the query server

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/query-server#63]
As per the discussion on gitter channel by @mariobehling different scrapers for each domain, similar to the loklak server be implemented.

**Comment by enigmaeth** [comment]
@nikhilrayaprolu I haven't gone through the loklak server's code much, but by this do you mean that the scrapers for different domains should be in separate files? Could you please provide me the link to loklak server's implementation so that I can take a look?

**Comment by nikhilrayaprolu** [comment]
loklak_server has something like this,
https://github.com/loklak/loklak_server/blob/development/src/org/loklak/harvester/TwitterScraper.java
https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/GenericScraper.java
https://github.com/loklak/loklak_server/blob/development/src/org/loklak/harvester/WeiboInfoScraper.java
https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/QuoraProfileScraper.java
https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/GithubProfileScraper.java
https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/InstagramProfileScraper.java
where individual scrappers are implemented for each site.

**Comment by Pk13055** [comment]
@nikhilrayaprolu  Can I pick this up?

**Comment by Pk13055** [comment]
Currently working on this, will submit a PR soon.
